# LLM Customer Churn Insight Tool
## Customer Churn Insight Analysis System Based on LLM + RAG

---

# Introduction

## 1.1 Project Background

In the telecom industry, **Customer Churn** is a critical business problem. Acquiring new customers typically costs 5-7 times more than retaining existing ones, making it commercially valuable to understand churn causes and take preventive measures.

Traditional churn analysis mainly relies on **structured data** (such as tenure, charges, service types) for statistical analysis or machine learning modeling. However, this approach overlooks an important information source: **customer feedback text**. The dissatisfaction, complaints, and suggestions expressed in customer feedback often reveal the deeper causes of churn.

This project combines **Large Language Models (LLM)** and **Retrieval-Augmented Generation (RAG)** technology to build an intelligent analysis system that can understand customer feedback and answer business questions.

## 1.2 Project Objectives

Build an **LLM-powered Customer Insight Tool** capable of:

1. **Retrieving Relevant Information**: Retrieve the most relevant customer data from the feedback database based on user queries
2. **Generating Root Cause Analysis**: Identify the main reasons for customer churn (Root Cause Analysis)
3. **Assessing Risk Levels**: Evaluate the severity of issues (Churn Risk Assessment)
4. **Providing Action Recommendations**: Offer specific, actionable improvement measures (Actionable Recommendations)
5. **Supporting Citation Traceability**: All conclusions are backed by specific customer IDs as evidence (Citations)

## 1.3 Technical Approach

This project adopts a **RAG (Retrieval-Augmented Generation)** architecture:

```mermaid
%%{init: {'theme': 'dark', 'themeVariables': { 'fontSize': '14px', 'fontFamily': 'arial', 'primaryColor': '#1a1a2e', 'primaryTextColor': '#fff', 'primaryBorderColor': '#4a9eff', 'lineColor': '#4a9eff'}}}%%
flowchart LR
    subgraph Input[" "]
        A[/"🔍 User Query"/]
    end

    subgraph Retrieval["Hybrid Search"]
        direction TB
        B1["📊 Vector Search<br/>Semantic Similarity"]
        B2["🔤 BM25 Search<br/>Keyword Matching"]
    end

    subgraph Process[" "]
        C[("📄 Top-K<br/>Relevant Docs")]
        D["🤖 LLM Analysis<br/>Qwen2.5-7B"]
    end

    subgraph Output[" "]
        E["📊 Analysis Report<br/>Summary+Actions+Citations"]
    end

    A --> B1 & B2
    B1 & B2 --> C
    C --> D
    D --> E

    style Input fill:#0f3460,stroke:#ffd700,stroke-width:2px
    style Retrieval fill:#16213e,stroke:#00d9ff,stroke-width:2px
    style Process fill:#1a1a2e,stroke:#00ff88,stroke-width:2px
    style Output fill:#3d1a4a,stroke:#bf7fff,stroke-width:2px
    style A fill:#0f3460,stroke:#ffd700,color:#fff
    style B1 fill:#1e3a5f,stroke:#00ff88,color:#fff
    style B2 fill:#1e3a5f,stroke:#00ff88,color:#fff
    style C fill:#2d4a3e,stroke:#00ff88,color:#fff
    style D fill:#4a1942,stroke:#ff6b9d,color:#fff
    style E fill:#3d1a4a,stroke:#bf7fff,color:#fff
```

### Why RAG?

| Approach | Pros | Cons |
|------|------|------|
| **Ask LLM Directly** | Simple and fast | Cannot access private data, may hallucinate |
| **Fine-tuning** | Model internalizes domain knowledge | High cost, data updates require retraining |
| **RAG** | Based on real data, traceable, easy to update | Requires building a retrieval system |

RAG is currently the mainstream approach for enterprise LLM applications, especially suitable for scenarios that require **analysis based on private data**.

---

# 2. Data Introduction

## 2.1 Data Source

This project uses the **Telco Customer Churn with Realistic Customer Feedback** dataset from Kaggle.

- **Data Link**: [https://www.kaggle.com/datasets/beatafaron/telco-customer-churn-realistic-customer-feedback](https://www.kaggle.com/datasets/beatafaron/telco-customer-churn-realistic-customer-feedback)
- **License**: CC BY 4.0 (Attribution 4.0 International)
- **Data Scale**: 7,043 customer records

This dataset is based on the classic IBM Telco Customer Churn dataset, with **LLM-generated simulated feedback text for each customer**, making the dataset contain both structured data and unstructured text.

## 2.2 Data Files Description

The downloaded data contains the following files:

| File Name | Size | Rows | Description |
|--------|------|------|------|
| `telco_churn_with_all_feedback.csv` | 5.6 MB | 7,043 | **Main data file**, contains complete customer info and feedback |
| `telco_prep.csv` | 5.8 MB | 7,032 | Preprocessed version, values converted to lowercase, added `feedback_length` and `sentiment` columns |
| `telco_noisy_feedback_prep.csv` | 1.7 MB | 7,032 | Version with some feedback missing, for testing system robustness |
| `model_with_feedback.pkl` | 27 KB | - | Pre-trained sentiment analysis model (pickle format) |

**This project uses `telco_churn_with_all_feedback.csv` as the main data source** because it contains complete feedback for all customers.

## 2.3 Variable Details

### 2.3.1 Customer Identifier

| Variable | Type | Description | Example |
|--------|------|------|------|
| `customerID` | String | Unique customer identifier | "7590-VHVEG" |

### 2.3.2 Demographics

| Variable | Type | Values | Description |
|--------|------|------|------|
| `gender` | String | Female, Male | Customer gender |
| `SeniorCitizen` | Integer | 0, 1 | Whether the customer is a senior citizen (65+)<br>0 = No, 1 = Yes |
| `Partner` | String | Yes, No | Whether the customer has a partner/spouse |
| `Dependents` | String | Yes, No | Whether the customer has dependents (e.g., children) |

### 2.3.3 Account Information

| Variable | Type | Values/Range | Description |
|--------|------|-----------|------|
| `tenure` | Integer | 0 - 72 | Tenure in months<br>0 indicates a new account opened this month |
| `Contract` | String | Month-to-month,<br>One year,<br>Two year | Contract type |
| `PaperlessBilling` | String | Yes, No | Whether the customer uses paperless billing |
| `PaymentMethod` | String | Electronic check,<br>Mailed check,<br>Bank transfer (automatic),<br>Credit card (automatic) | Payment method |

### 2.3.4 Services

| Variable | Type | Values | Description |
|--------|------|------|------|
| `PhoneService` | String | Yes, No | Whether the customer subscribes to phone service |
| `MultipleLines` | String | Yes, No,<br>No phone service | Whether the customer has multiple phone lines |
| `InternetService` | String | DSL,<br>Fiber optic,<br>No | Internet service type |
| `OnlineSecurity` | String | Yes, No,<br>No internet service | Online security service |
| `OnlineBackup` | String | Yes, No,<br>No internet service | Online backup service |
| `DeviceProtection` | String | Yes, No,<br>No internet service | Device protection service |
| `TechSupport` | String | Yes, No,<br>No internet service | Tech support service |
| `StreamingTV` | String | Yes, No,<br>No internet service | Streaming TV service |
| `StreamingMovies` | String | Yes, No,<br>No internet service | Streaming movies service |

### 2.3.5 Charges

| Variable | Type | Range | Description |
|--------|------|------|------|
| `MonthlyCharges` | Float | $18.25 - $118.75 | Monthly charges (USD) |
| `TotalCharges` | String* | - | Total charges (USD)<br>*Note: Original data is string type, needs conversion |

### 2.3.6 Target Variable

| Variable | Type | Values | Description |
|--------|------|------|------|
| `Churn` | String | Yes, No | **Whether churned**<br>Yes = Churned (left)<br>No = Retained (active) |

### 2.3.7 Text Data

| Variable | Type | Description |
|--------|------|------|
| `PromptInput` | String | LLM prompt used to generate feedback (not used in this project) |
| `CustomerFeedback` | String | **Customer feedback text** (core data for this project)<br>Length approximately 277-840 characters |

## 2.4 Data Characteristics

1. **High Completeness**: All 7,043 records have customer feedback text
2. **Clear Labels**: Churn labels are clear, facilitating analysis
3. **Information-Rich**: Combination of structured data + unstructured text
4. **Class Imbalance**: Churn rate is approximately 26.5% (1,869 churned vs 5,174 retained)

---

# 3. Project Structure

```
LLM-Project/
├── data/                                    # Data directory
│   ├── telco_churn_with_all_feedback.csv   # Main data file
│   ├── telco_prep.csv                      # Preprocessed data
│   ├── telco_noisy_feedback_prep.csv       # Noisy feedback data
│   ├── model_with_feedback.pkl             # Pre-trained model
│   ├── faiss_index.bin                     # FAISS vector index (generated after running)
│   └── index_data.pkl                      # Index metadata (generated after running)
├── venv/                                    # Python virtual environment
├── LLM-Churn-RAG-Fintuning.ipynb           # Main notebook (this file)
├── Using_tool_required_for_customer_service.ipynb  # Reference example code
└── README.md                               # Project documentation
```

---

# 4. Key Terminology

| Term | Full Name | Explanation |
|------|----------|------|
| **RAG** | Retrieval-Augmented Generation | First retrieves relevant information from a knowledge base, then has the LLM generate answers based on that information, avoiding "hallucinations" |
| **Embedding** | Vector Embedding | Converts text into high-dimensional vectors; semantically similar texts are closer in vector space |
| **FAISS** | Facebook AI Similarity Search | Efficient vector similarity search library developed by Meta, supporting fast search over billions of vectors |
| **BM25** | Best Matching 25 | Classic keyword retrieval algorithm that calculates relevance based on term frequency and document frequency |
| **RRF** | Reciprocal Rank Fusion | Algorithm for merging multiple ranked result lists |
| **Chunk** | Text Chunk | Splitting long documents into smaller segments for easier retrieval and processing |
| **Cosine Similarity** | - | Measures the directional similarity between two vectors, range [-1, 1] |
| **Prompt Engineering** | - | Designing effective prompts to guide LLM to produce desired outputs |
| **Hallucination** | - | LLM generating information that appears plausible but is actually non-existent or incorrect |
| **Citation** | - | Reference pointing to the specific data source supporting a conclusion |

---

# 5. Runtime Environment

## 5.1 Requirements

- Python 3.9+
- Approximately 2GB disk space (for models and indexes)
- Google Colab (free T4 GPU)

## 5.2 Dependencies

```
pandas>=2.0
numpy>=1.24
sentence-transformers>=2.2
faiss-cpu>=1.7
rank_bm25>=0.2
transformers>=4.36
peft>=0.7
bitsandbytes>=0.41
accelerate>=0.25
```

## 5.3 Getting Started

```bash
# 1. Navigate to the project directory
cd /Users/ricky/Desktop/LLM-Project

# 2. Activate virtual environment
source venv/bin/activate

# 3. Start Jupyter
jupyter notebook

# 4. In Jupyter, select Kernel: "LLM Project (venv)"
```

---

# 6. Project Phase Overview

| Phase | Name | Content | Key Technologies |
|-------|------|------|----------|
| **Phase 1** | Data Preparation | Load, clean, build documents | Pandas, Data Preprocessing |
| **Phase 2** | Indexing & Retrieval | Vectorize, build indexes, hybrid search | Sentence-Transformers, FAISS, BM25, RRF |
| **Phase 3** | LLM Integration | Prompt design, RAG Pipeline | Qwen2.5-7B-Instruct, Prompt Engineering |
| **Phase 4** | Output & Evaluation | Formatted output, citation validation | JSON Parsing, Quality Assessment |

---

# Phase 1: Data Ingestion

In a RAG system, **data quality directly determines the quality of the final output**. The goals of Phase 1 are:

1. Load raw data (structured + unstructured)
2. Data exploration and quality checks
3. Data cleaning and preprocessing
4. Build document formats suitable for retrieval

## 1.0 Environment Setup

First, import the necessary Python libraries and configure the runtime environment.

In [17]:
# ============================================
# LLM Customer Churn Insight Tool
# LLM + RAG + Customer Feedback Analysis
# ============================================

# Phase 1: Data Ingestion
# Phase 2: Indexing & Retrieval
# Phase 3: LLM Integration
# Phase 4: Output & Evaluation

# --------------------------------------------
# 1.0 Environment Setup & Dependency Imports
# --------------------------------------------

import os
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 200)

print("Environment setup complete ✓")

环境配置完成 ✓


## 1.1 Load Data

We are using the **Telco Customer Churn** dataset, which contains:

- **Structured Data**: Customer demographics, subscribed services, billing info, churn labels
- **Unstructured Data**: Customer feedback text (CustomerFeedback)

Data source: [Kaggle - Telco Customer Churn with Realistic Feedback](https://www.kaggle.com/datasets/beatafaron/telco-customer-churn-realistic-customer-feedback)

In [18]:
# --------------------------------------------
# 1.1 Load Data
# --------------------------------------------

# Data path
DATA_DIR = './data'

# Load main data file (contains customer info + feedback)
df_main = pd.read_csv(f'{DATA_DIR}/telco_churn_with_all_feedback.csv')

print(f"Dataset size: {df_main.shape[0]} rows, {df_main.shape[1]} columns")
print(f"\nColumns:\n{df_main.columns.tolist()}")

数据集大小: 7043 行, 23 列

列名:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn', 'PromptInput', 'CustomerFeedback']


### Output Analysis

The dataset contains **7,043 customer records** and **23 feature columns**:

| Category | Fields |
|------|------|
| **Customer ID** | customerID |
| **Demographics** | gender, SeniorCitizen, Partner, Dependents |
| **Account Info** | tenure, Contract, PaperlessBilling, PaymentMethod |
| **Service Subscriptions** | PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies |
| **Charges** | MonthlyCharges, TotalCharges |
| **Target Variable** | Churn |
| **Text Data** | CustomerFeedback |

---

## 1.2 Data Exploration

View the first few rows of data to understand the basic structure.

In [19]:
# --------------------------------------------
# 1.2 Data Exploration - Basic Info
# --------------------------------------------

# View first few rows
df_main.head(3)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   

  PaperlessBilling     PaymentMethod  MonthlyCharges TotalCharges Churn  \
0              Yes  Electronic check           29.85        29.85    No   
1               No      Mailed check           56.95       1889.5    No   
2              Yes      Mailed check           53.85       108.15   Yes   

                                                                                                                                                                                               PromptInput  \
0  Write a realistic customer feedback based on this profile:\nChurn: No\nTenure: 1 months\nContract type: Month-to-month\nMonthly Charges: $29.85\nInternet Service: DSL\nPayment Method: Electronic c...   
1          Write a realistic customer feedback based on this profile:\nChurn: No\nTenure: 34 months\nContract type: One year\nMonthly Charges: $56.95\nInternet Service: DSL\nPayment Method: Mailed check   
2    Write a realistic customer feedback based on this profile:\nChurn: Yes\nTenure: 2 months\nContract type: Month-to-month\nMonthly Charges: $53.85\nInternet Service: DSL\nPayment Method: Mailed check   

                                                                                                                                                                                          CustomerFeedback  
0  I have been using the DSL internet service from this provider for the past month and so far, I am satisfied with the service. The connection has been reliable and the speed is sufficient for my ne...  
1  I have been a customer with this company for over two and a half years now and I have been very satisfied with their service. The DSL internet has been reliable and the monthly charges are reasona...  
2  I recently signed up for DSL internet service with this provider two months ago on a month-to-month contract. Unfortunately, I have already decided to churn and switch to a different provider. The...

### Data Type Check

Check the data type and missing values for each column. This step is important because:
- Numeric fields may be incorrectly identified as strings (e.g., TotalCharges)
- Missing values need to be filled or removed in subsequent processing

In [25]:
# Data type and missing value check
print("=" * 50)
print("Data Types:")
print("=" * 50)
print(df_main.dtypes)
print("\n" + "=" * 50)
print("Missing Value Statistics:")
print("=" * 50)
print(df_main.isnull().sum())

数据类型:
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
PromptInput          object
CustomerFeedback     object
dtype: object

缺失值统计:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     

### Output Analysis

**Issues Found**:
- `TotalCharges` is `object` type instead of `float64`, indicating non-numeric characters (such as empty strings) that need conversion
- There appear to be no missing values (`isnull().sum()` is all 0), but empty strings are not detected as NaN

---

## 1.3 Churn Analysis

Analyze the distribution of the target variable (Churn).

In [21]:
# --------------------------------------------
# 1.3 Data Exploration - Churn Analysis
# --------------------------------------------

# Churn rate statistics
churn_counts = df_main['Churn'].value_counts()
print("Churn Statistics:")
print(churn_counts)
print(f"\nChurn rate: {(df_main['Churn'] == 'Yes').mean() * 100:.2f}%")

流失统计:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

流失率: 26.54%


### Output Analysis

- **Churned Customers**: 1,869 (26.54%)
- **Retained Customers**: 5,174 (73.46%)

This is a typical **Imbalanced Dataset**, with churned customers comprising about 1/4. In actual business, this churn rate is quite high and requires focused analysis of churn causes.

---

## 1.4 Customer Feedback Analysis

View feedback text examples from churned and retained customers to understand text characteristics and differences.

In [22]:
# --------------------------------------------
# 1.4 Data Exploration - Customer Feedback Analysis
# --------------------------------------------

# Check customer feedback column
print("Customer Feedback Example (Churned):")
print("-" * 50)
churned_feedback = df_main[df_main['Churn'] == 'Yes']['CustomerFeedback'].iloc[0]
print(churned_feedback[:500] if len(churned_feedback) > 500 else churned_feedback)

print("\n" + "=" * 50)
print("\nCustomer Feedback Example (Retained):")
print("-" * 50)
retained_feedback = df_main[df_main['Churn'] == 'No']['CustomerFeedback'].iloc[0]
print(retained_feedback[:500] if len(retained_feedback) > 500 else retained_feedback)

客户反馈示例 (流失客户):
--------------------------------------------------
I recently signed up for DSL internet service with this provider two months ago on a month-to-month contract. Unfortunately, I have already decided to churn and switch to a different provider. The monthly charges of $53.85 were reasonable, but I found the internet service to be unreliable and slow. Additionally, having to mail in a check for payment was inconvenient and outdated. I would not recommend this provider to others looking for reliable and convenient internet service.


客户反馈示例 (非流失客户):
--------------------------------------------------
I have been using the DSL internet service from this provider for the past month and so far, I am satisfied with the service. The connection has been reliable and the speed is sufficient for my needs. The monthly charges are reasonable at $29.85 and I appreciate the convenience of paying through electronic check. Overall, I have had a positive experience and would recommend this 

### Output Analysis

By comparing feedback from both customer types, clear **sentiment differences** can be observed:

| Customer Type | Feedback Characteristics |
|----------|----------|
| **Churned** | Uses negative words (unreliable, slow, inconvenient), clearly expresses dissatisfaction and intent to leave |
| **Retained** | Uses positive words (satisfied, reliable, reasonable), expresses willingness to recommend |

These feedback texts will be the **core knowledge base** of the RAG system, and the LLM will analyze based on these real feedbacks.

---

## 1.5 Data Cleaning & Preprocessing

Perform necessary data cleaning:
1. Drop unnecessary columns (PromptInput is the prompt used to generate feedback, not needed)
2. Convert data types (TotalCharges to numeric)
3. Handle missing values
4. Create numeric target variable (for easier analysis)

In [27]:
# --------------------------------------------
# 1.5 Data Cleaning & Preprocessing
# --------------------------------------------

# Create working copy
df = df_main.copy()

# 1. Drop unnecessary columns (PromptInput was used to generate feedback, not needed)
if 'PromptInput' in df.columns:
    df = df.drop(columns=['PromptInput'])
    print("Dropped PromptInput column")

# 2. Handle empty values in TotalCharges (convert to numeric)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print(f"TotalCharges missing values: {df['TotalCharges'].isnull().sum()}")

# 3. Fill missing values (use MonthlyCharges since new customers may have empty TotalCharges)
df['TotalCharges'] = df['TotalCharges'].fillna(df['MonthlyCharges'])

# 4. Convert Churn to numeric (for easier analysis)
df['Churn_Binary'] = (df['Churn'] == 'Yes').astype(int)

print(f"\nDataset size after cleaning: {df.shape}")
print("Data cleaning complete ✓")

已删除 PromptInput 列
TotalCharges 缺失值: 11

清洗后数据集大小: (7043, 23)
数据清洗完成 ✓


### Output Analysis

- After successfully converting `TotalCharges` to numeric, **11 missing values** were found
- These missing values correspond to new customers (tenure=0), filling with `MonthlyCharges` is reasonable
- Created `Churn_Binary` column (0=Retained, 1=Churned) for numeric calculations

## 1.6 Feedback Text Processing

Check the validity of feedback text to ensure all records have usable feedback content.

In [28]:
# --------------------------------------------
# 1.6 Feedback Text Processing
# --------------------------------------------

# Check feedback text validity
df['feedback_length'] = df['CustomerFeedback'].fillna('').apply(len)
df['has_feedback'] = df['feedback_length'] > 10  # At least 10 characters counts as valid feedback

print(f"Valid feedback count: {df['has_feedback'].sum()} / {len(df)}")
print(f"Valid feedback ratio: {df['has_feedback'].mean() * 100:.2f}%")

# Feedback length statistics
print(f"\nFeedback Length Statistics:")
print(df[df['has_feedback']]['feedback_length'].describe())

有效反馈数量: 7043 / 7043
有效反馈比例: 100.00%

反馈长度统计:
count    7043.000000
mean      460.571205
std        68.197917
min       277.000000
25%       414.000000
50%       454.000000
75%       499.000000
max       840.000000
Name: feedback_length, dtype: float64


### Output Analysis

- **100% of customers have valid feedback** (length > 10 characters)
- Feedback length statistics: average 461 characters, range 277-840 characters
- This means we can build documents for all 7,043 customers

---

## 1.7 Build RAG Documents

**This is the most critical step in Phase 1**. We need to integrate structured data and unstructured feedback into a unified document format.

### Why Build Documents?

The retrieval unit in a RAG system is a "document". A good document should:
1. **Self-contained**: Contains sufficient context for the LLM to understand without additional information
2. **Structured**: Information is clearly organized for easy extraction by the LLM
3. **Identifiable**: Contains a unique identifier (Customer ID) for citation traceability

In [29]:
# --------------------------------------------
# 1.7 Prepare RAG Documents
# --------------------------------------------

# Create a comprehensive document for each customer (for RAG retrieval)
def create_customer_document(row):
    """
    Combine customer structured data and feedback into a single document
    """
    doc = f"""Customer ID: {row['customerID']}
Churn Status: {row['Churn']}

Customer Profile:
- Gender: {row['gender']}
- Senior Citizen: {'Yes' if row['SeniorCitizen'] == 1 else 'No'}
- Partner: {row['Partner']}
- Dependents: {row['Dependents']}
- Tenure: {row['tenure']} months

Services:
- Phone Service: {row['PhoneService']}
- Internet Service: {row['InternetService']}
- Online Security: {row['OnlineSecurity']}
- Tech Support: {row['TechSupport']}
- Streaming TV: {row['StreamingTV']}
- Streaming Movies: {row['StreamingMovies']}

Contract & Billing:
- Contract: {row['Contract']}
- Monthly Charges: ${row['MonthlyCharges']}
- Total Charges: ${row['TotalCharges']:.2f}
- Payment Method: {row['PaymentMethod']}

Customer Feedback:
{row['CustomerFeedback']}
"""
    return doc

# Only create documents for customers with feedback
df_with_feedback = df[df['has_feedback']].copy()
df_with_feedback['document'] = df_with_feedback.apply(create_customer_document, axis=1)

print(f"Created {len(df_with_feedback)} customer documents")
print("\nExample Document:")
print("=" * 50)
print(df_with_feedback['document'].iloc[0][:800])

已创建 7043 个客户文档

示例文档:
Customer ID: 7590-VHVEG
Churn Status: No

Customer Profile:
- Gender: Female
- Senior Citizen: No
- Partner: Yes
- Dependents: No
- Tenure: 1 months

Services:
- Phone Service: No
- Internet Service: DSL
- Online Security: No
- Tech Support: No
- Streaming TV: No
- Streaming Movies: No

Contract & Billing:
- Contract: Month-to-month
- Monthly Charges: $29.85
- Total Charges: $29.85
- Payment Method: Electronic check

Customer Feedback:
I have been using the DSL internet service from this provider for the past month and so far, I am satisfied with the service. The connection has been reliable and the speed is sufficient for my needs. The monthly charges are reasonable at $29.85 and I appreciate the convenience of paying through electronic check. Overall, I have had a positive experience and


### Output Analysis

Successfully created **7,043 customer documents**. Each document contains:
- Customer ID and churn status (for citation)
- Customer profile (demographics)
- Service subscriptions
- Charges and contract information
- Original customer feedback

This format ensures the LLM can see both **quantitative data** (charges, tenure) and **qualitative data** (feedback text) during analysis.

## Phase 1 Summary

In [30]:
# --------------------------------------------
# Phase 1 Complete - Data Summary
# --------------------------------------------

print("=" * 50)
print("Phase 1: Data Preparation Complete")
print("=" * 50)
print(f"Total customers: {len(df)}")
print(f"Customers with feedback: {len(df_with_feedback)}")
print(f"Churned customers: {df['Churn_Binary'].sum()}")
print(f"Churn rate: {df['Churn_Binary'].mean() * 100:.2f}%")
print(f"\nFeedback ratio among churned customers: {df_with_feedback['Churn_Binary'].mean() * 100:.2f}%")

Phase 1: 数据准备完成
总客户数: 7043
有反馈的客户数: 7043
流失客户数: 1869
流失率: 26.54%

流失客户中有反馈的比例: 26.54%


### Phase 1 Complete

Key achievements of the data preparation phase:
- Loaded and cleaned 7,043 customer records
- Churn rate is 26.54% (1,869 churned customers)
- Built 7,043 structured documents, ready for indexing

---

# Phase 2: Indexing & Retrieval

Phase 2 is the **core technical component** of the RAG system, aiming to achieve efficient and accurate document retrieval.

## Why Is Retrieval Needed?

The LLM's context window is limited (e.g., Qwen2.5-7B has ~32K tokens) and cannot process all 7,043 documents at once. We need to:
1. Quickly find the most relevant documents (e.g., Top 5) based on user queries
2. Only feed these relevant documents to the LLM for analysis

## Retrieval Strategy: Hybrid Retrieval

We adopt a **vector search + keyword search** hybrid strategy:

| Method | Advantage | Disadvantage |
|------|------|------|
| **Vector Search** | Understands semantic similarity (e.g., "cancel service" ~ "unsubscribe") | May miss exact keyword matches |
| **BM25 Keyword Search** | Exact keyword matching, high interpretability | Cannot understand synonyms and semantics |
| **Hybrid Search** | Combines advantages of both | Requires designing a fusion strategy |

## 2.0 Load Dependencies

Import libraries needed for Phase 2:
- `sentence-transformers`: Generate text vector embeddings
- `faiss`: Efficient vector similarity search
- `rank_bm25`: BM25 keyword retrieval algorithm

In [31]:
# ============================================
# Phase 2: Indexing & Retrieval
# ============================================

# Install required dependencies (if not already installed)
# !pip install sentence-transformers faiss-cpu rank_bm25 -q

from sentence_transformers import SentenceTransformer
import faiss
from rank_bm25 import BM25Okapi
import re

print("Phase 2 dependencies loaded ✓")

Phase 2 依赖加载完成 ✓


## 2.1 Text Preprocessing

Before creating vector embeddings, the text needs to be standardized:
- Merge extra whitespace characters
- Trim leading and trailing spaces

This step ensures consistent text formatting, avoiding meaningless differences that affect retrieval performance.

In [32]:
# --------------------------------------------
# 2.1 Text Preprocessing
# --------------------------------------------

def preprocess_text(text):
    """
    Clean text: remove extra whitespace
    """
    text = re.sub(r'\s+', ' ', text)  # Merge extra whitespace
    text = text.strip()
    return text

# Preprocess all documents
documents = df_with_feedback['document'].apply(preprocess_text).tolist()
customer_ids = df_with_feedback['customerID'].tolist()

print(f"Preprocessing complete: {len(documents)} documents")
print(f"Average document length: {np.mean([len(d) for d in documents]):.0f} characters")

预处理完成: 7043 个文档
平均文档长度: 918 字符


## 2.2 Create Vector Embeddings

### What Are Vector Embeddings?

Vector embeddings are a technique for mapping text to high-dimensional vector space. In this space:
- **Semantically similar texts** are closer together
- **Semantically different texts** are farther apart

For example:
- "I want to cancel my service" and "I'm leaving this company" would have very close vectors
- "I love this service" and "I want to cancel" would have distant vectors

### Embedding Model Selection

We use the **BGE (BAAI General Embedding)** model:
- Model: `BAAI/bge-base-en-v1.5`
- Dimensions: 768
- Features: Excellent performance on multiple retrieval benchmarks, fully open-source and free

### Mathematical Principle

Given a text $t$, the embedding model $f$ maps it to a vector:

$$\vec{v} = f(t) \in \mathbb{R}^{768}$$

The similarity between two texts is calculated using **cosine similarity**:

$$\text{similarity}(t_1, t_2) = \cos(\vec{v_1}, \vec{v_2}) = \frac{\vec{v_1} \cdot \vec{v_2}}{||\vec{v_1}|| \cdot ||\vec{v_2}||}$$

When vectors are normalized ($||\vec{v}|| = 1$), cosine similarity equals the dot product.

In [34]:
# --------------------------------------------
# 2.2 Create Vector Embeddings
# --------------------------------------------

# Load embedding model (using BGE model, high performance and free)
print("Loading embedding model...")
embedding_model = SentenceTransformer('BAAI/bge-base-en-v1.5')

# Generate document embeddings
print("Generating document embeddings (may take a few minutes)...")
document_embeddings = embedding_model.encode(
    documents, 
    show_progress_bar=True,
    normalize_embeddings=True  # Normalize for cosine similarity
)

print(f"\nEmbedding dimensions: {document_embeddings.shape}")
print("Vector embeddings created ✓")

加载嵌入模型...
生成文档嵌入 (可能需要几分钟)...


Batches: 100%|██████████| 221/221 [01:47<00:00,  2.06it/s]


嵌入维度: (7043, 768)
向量嵌入创建完成 ✓


### Output Analysis

- Successfully generated vector embeddings for **7,043 documents**
- Each vector has **768** dimensions
- Used `normalize_embeddings=True` for L2 normalization, allowing inner product to replace cosine similarity

## 2.3 Build Vector Store (FAISS Index)

### What Is FAISS?

**FAISS (Facebook AI Similarity Search)** is an efficient vector similarity search library developed by Meta, capable of:
- Completing similarity search over millions of vectors in milliseconds
- Supporting GPU acceleration
- Providing multiple index types (exact search, approximate search)

### Index Type Selection

We use `IndexFlatIP` (Flat Index with Inner Product):
- **Flat**: Exact search, no approximation
- **IP**: Inner Product, since vectors are normalized, equivalent to cosine similarity

For 7,043 documents, exact search performance is already sufficient. For million-scale documents, consider using approximate indexes like `IndexIVFFlat`.

In [38]:
# --------------------------------------------
# 2.3 Build Vector Store (FAISS)
# --------------------------------------------

# Create FAISS index
dimension = document_embeddings.shape[1]
faiss_index = faiss.IndexFlatIP(dimension)  # Inner product (equivalent to cosine similarity since vectors are normalized)
faiss_index.add(document_embeddings.astype('float32'))

print(f"FAISS index created")
print(f"Vectors in index: {faiss_index.ntotal}")

FAISS 索引已创建
索引中的向量数: 7043


## 2.4 Build BM25 Index

### What Is BM25?

**BM25 (Best Matching 25)** is a classic keyword retrieval algorithm widely used in search engines. It is based on a bag-of-words model and considers:
- **Term Frequency (TF)**: The number of times a term appears in a document
- **Inverse Document Frequency (IDF)**: How rare a term is across the entire corpus
- **Document Length Normalization**: Prevents unfair advantage for longer documents

### BM25 Formula

For query $Q$ and document $D$, the BM25 score is:

$$\text{BM25}(D, Q) = \sum_{i=1}^{n} \text{IDF}(q_i) \cdot \frac{f(q_i, D) \cdot (k_1 + 1)}{f(q_i, D) + k_1 \cdot (1 - b + b \cdot \frac{|D|}{\text{avgdl}})}$$

Where:
- $f(q_i, D)$: Term frequency of $q_i$ in document $D$
- $|D|$: Document length
- $\text{avgdl}$: Average document length
- $k_1$, $b$: Tuning parameters (typically $k_1 = 1.5$, $b = 0.75$)
- $\text{IDF}(q_i)$: Inverse document frequency of term $q_i$

### Advantages of BM25

- Excellent for **exact keyword matching**
- Computationally efficient, no GPU required
- Results are interpretable (can identify which terms matched)

In [39]:
# --------------------------------------------
# 2.4 Build BM25 Index (Keyword Search)
# --------------------------------------------

# Tokenization
tokenized_docs = [doc.lower().split() for doc in documents]

# Create BM25 index
bm25_index = BM25Okapi(tokenized_docs)

print(f"BM25 index created")
print(f"Vocabulary size: {len(bm25_index.idf)}")

BM25 索引已创建
词汇表大小: 17770


### Output Analysis

- BM25 index contains **17,770 unique terms**
- Tokenization uses simple whitespace splitting (suitable for English); Chinese would require tools like jieba

## 2.5 Implement Hybrid Search

### Why Hybrid?

Each retrieval method has limitations:

| Query Example | Vector Search | BM25 |
|----------|----------|------|
| "customers unhappy with service" | Can understand "unhappy" semantics | May miss "dissatisfied" documents |
| "DSL internet" | May return other types of network services | Precisely matches "DSL" |

Hybrid search combines both advantages, improving **recall** and **precision**.

### Fusion Algorithm: RRF (Reciprocal Rank Fusion)

**RRF** is a simple and effective rank fusion algorithm with the formula:

$$\text{RRF}(d) = \sum_{r \in R} \frac{1}{k + r(d)}$$

Where:
- $R$: All retrieval result lists (vector search and BM25 in this project)
- $r(d)$: The rank of document $d$ in a result list (starting from 1)
- $k$: Smoothing constant (typically 60)

**RRF Characteristics**:
- No need to normalize scores from different retrieval methods
- Gives higher weight to top-ranked documents
- Parameter $k$ controls the impact of rank differences

### Weight Parameter α

For document d, its RRF fusion score is defined as:

$$
\mathrm{RRF}(d)
=
\alpha \cdot \frac{1}{k + r_{\text{faiss}}(d)}
+
(1 - \alpha) \cdot \frac{1}{k + r_{\text{bm25}}(d)}
$$

Where:

* $d$: Candidate document
* $r_{\text{faiss}}(d)$: Rank of document $d$ in vector search (FAISS) results (starting from 1)
* $r_{\text{bm25}}(d)$: Rank of document $d$ in BM25 keyword search results (starting from 1)
* $k$: RRF smoothing constant, used to reduce the impact of rank differences, typically $k = 60$
* $\alpha \in [0, 1]$: Weight parameter controlling the relative importance of vector search vs BM25 search

  * $\alpha = 0.5$: Equal weight for both methods
  * $\alpha > 0.5$: More emphasis on vector search
  * $\alpha < 0.5$: More emphasis on BM25 search


In [40]:
# --------------------------------------------
# 2.5 Implement Hybrid Search
# --------------------------------------------

def vector_search(query, k=10):
    """
    Vector search
    """
    query_embedding = embedding_model.encode([query], normalize_embeddings=True)
    scores, indices = faiss_index.search(query_embedding.astype('float32'), k)
    return list(zip(indices[0], scores[0]))

def bm25_search(query, k=10):
    """
    BM25 keyword search
    """
    tokenized_query = query.lower().split()
    scores = bm25_index.get_scores(tokenized_query)
    top_indices = np.argsort(scores)[::-1][:k]
    return [(idx, scores[idx]) for idx in top_indices]

def hybrid_search(query, k=10, alpha=0.5):
    """
    Hybrid search (RRF - Reciprocal Rank Fusion)
    
    Args:
        query: Query text
        k: Number of results to return
        alpha: Vector search weight (1-alpha is the BM25 weight)
    """
    # Get results from both search methods
    vector_results = vector_search(query, k=k*2)
    bm25_results = bm25_search(query, k=k*2)
    
    # RRF fusion
    rrf_scores = {}
    rrf_k = 60  # RRF constant
    
    for rank, (idx, _) in enumerate(vector_results):
        rrf_scores[idx] = rrf_scores.get(idx, 0) + alpha / (rrf_k + rank + 1)
    
    for rank, (idx, _) in enumerate(bm25_results):
        rrf_scores[idx] = rrf_scores.get(idx, 0) + (1 - alpha) / (rrf_k + rank + 1)
    
    # Sort and return
    sorted_results = sorted(rrf_scores.items(), key=lambda x: x[1], reverse=True)[:k]
    
    return sorted_results

print("Hybrid search functions defined ✓")

混合检索函数定义完成 ✓


## 2.6 Test Retrieval

Use a sample query to test the hybrid search system and verify the relevance of retrieval results.

In [45]:
# --------------------------------------------
# 2.6 Test Retrieval
# --------------------------------------------

# Test query
test_query = "customers who are unhappy with the internet service and want to cancel"

print(f"Test query: {test_query}")
print("=" * 50)

# Execute hybrid search
results = hybrid_search(test_query, k=3)

print("\nSearch Results:")
for rank, (idx, score) in enumerate(results, 1):
    print(f"\n--- Result {rank} (Score: {score:.4f}) ---")
    print(f"Customer ID: {customer_ids[idx]}")
    print(f"Churn: {df_with_feedback.iloc[idx]['Churn']}")
    # Show first 200 characters of feedback
    feedback = df_with_feedback.iloc[idx]['CustomerFeedback']
    print(f"Feedback: {feedback}")

测试查询: customers who are unhappy with the internet service and want to cancel

检索结果:

--- 结果 1 (Score: 0.0082) ---
Customer ID: 6598-RFFVI
Churn: Yes
Feedback: I am extremely dissatisfied with my experience with this service provider. Despite being promised internet service, I have not received any connection in the two months since signing up. The fact that I am locked into a one-year contract with monthly charges of $19.3 is unacceptable. The automatic credit card payment method adds insult to injury, as I am essentially paying for a service I am not receiving. I will be looking to cancel my contract and find a more reliable provider as soon as possible.

--- 结果 2 (Score: 0.0082) ---
Customer ID: 7321-ZNSLA
Churn: No
Feedback: I have been a customer of this DSL internet service provider for the past 13 months and I am pleased to say that I have not experienced any issues that would make me want to churn. The monthly charges of $40.55 are reasonable and the service provided has been re

### Output Analysis

The retrieval test results show the system is working properly:

| Rank | Customer ID | Churn Status | Analysis |
|------|---------|----------|------|
| 1 | 6598-RFFVI | Yes | Retrieved a churned customer dissatisfied with internet service |
| 2 | 7321-ZNSLA | No | Provides a contrasting perspective (satisfied customer) |
| 3 | 4871-JTKJF | Yes | Retrieved another customer who churned due to service quality |

The retrieval system successfully found customer feedback relevant to the query, including both churned and retained customers, which is valuable for comprehensive analysis.

---

# Phase 3: LLM Integration

Phase 3 connects the retrieval system with the large language model to build a complete **RAG Pipeline**.

## RAG Workflow

```mermaid
%%{init: {'theme': 'dark', 'themeVariables': { 'fontSize': '14px'}}}%%
flowchart LR
    A["🔍 User Query"] --> B["⚡ Hybrid Search"]
    B --> C["📄 Top-K Docs"]
    C --> D["📝 Build Prompt"]
    D --> E["🤖 Qwen2.5-7B"]
    E --> F["📊 Structured Output"]

    D -.-> G["System Prompt<br/>+ Context<br/>+ Query"]

    style A fill:#0f3460,stroke:#ffd700,color:#fff
    style B fill:#1e3a5f,stroke:#00ff88,color:#fff
    style C fill:#2d4a3e,stroke:#00ff88,color:#fff
    style D fill:#16213e,stroke:#00d9ff,color:#fff
    style E fill:#4a1942,stroke:#ff6b9d,color:#fff
    style F fill:#3d1a4a,stroke:#bf7fff,color:#fff
    style G fill:#1a1a2e,stroke:#888,color:#aaa
```

## Why RAG Instead of Asking the LLM Directly?

| Method | Pros | Cons |
|------|------|------|
| **Ask LLM Directly** | Simple | May hallucinate, cannot cite specific data |
| **RAG** | Based on real data, traceable citations | Requires building a retrieval system |

RAG makes LLM answers **verifiable**, which is crucial in business analysis scenarios.

## 3.0 Load Open-Source LLM Model

Load Qwen2.5-7B-Instruct (4-bit quantized) as the generation end of the RAG Pipeline. Using BitsAndBytes 4-bit quantization, VRAM usage is approximately 4.5 GB, fully supported by T4 GPU.

> **Warning: Starting from Phase 3, code needs to run on Google Colab (T4 GPU)**

In [52]:
# ============================================
# Phase 3: LLM Integration
# ⚠️ Run on Google Colab (T4 GPU)
# ============================================

# Install fine-tuning dependencies (needed for Phase 3-8)
# !pip install -q transformers peft bitsandbytes trl datasets accelerate

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch
import json

# 4-bit quantization config (NF4 + double quantization, maximize compression)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",             # NF4 quantization: information-theoretically optimal 4-bit data type
    bnb_4bit_compute_dtype=torch.bfloat16,  # Use bfloat16 precision for computation
    bnb_4bit_use_double_quant=True,         # Double quantization: further compress quantization parameters
)

MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"

print(f"Loading model: {MODEL_NAME} (4-bit quantization)...")
print("Estimated time: 2-3 minutes...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
model.eval()

print(f"\nModel loaded ✓")
print(f"GPU memory usage: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")
print(f"GPU total memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")

OpenAI 客户端初始化完成 ✓


## 3.1 Define Prompt Templates

### Prompt Engineering

Prompt design is a key factor affecting LLM output quality. A good prompt should:

1. **Define the Role**: Tell the LLM what expert it is
2. **Define the Task**: Clearly describe the work to be completed
3. **Specify the Format**: Require structured output (e.g., JSON)
4. **Provide Examples**: Show the expected output format
5. **Set Constraints**: Clearly define limitations and requirements

### Our Prompt Structure

```mermaid
%%{init: {'theme': 'dark', 'themeVariables': { 'fontSize': '14px'}}}%%
flowchart TB
    subgraph SP["🔧 System Prompt"]
        direction LR
        S1["👤 Role Definition<br/>Churn Analyst"]
        S2["📋 Output Format<br/>JSON Schema"]
        S3["📏 Analysis Guide<br/>Constraints"]
    end

    PLUS(("+"))

    subgraph UP["💬 User Prompt"]
        direction LR
        U1["❓ User Query"]
        U2["📊 Retrieved<br/>Customer Data"]
    end

    SP --> PLUS --> UP

    style SP fill:#1a1a2e,stroke:#4a9eff,stroke-width:2px
    style UP fill:#16213e,stroke:#00d9ff,stroke-width:2px
    style PLUS fill:#ffd700,stroke:#ffd700,color:#000
    style S1 fill:#0f3460,stroke:#ffd700,color:#fff
    style S2 fill:#0f3460,stroke:#ffd700,color:#fff
    style S3 fill:#0f3460,stroke:#ffd700,color:#fff
    style U1 fill:#1e3a5f,stroke:#00ff88,color:#fff
    style U2 fill:#1e3a5f,stroke:#00ff88,color:#fff
```

### Importance of Structured Output

We require the LLM to return JSON format so that:
- It can be easily parsed programmatically for downstream processing
- The output contains all necessary fields
- Automated validation is possible (e.g., checking if citations are valid)

In [53]:
# --------------------------------------------
# 3.1 Define Prompt Templates
# --------------------------------------------

SYSTEM_PROMPT = """You are a customer churn analysis expert. Based on the provided customer feedback and profile data, analyze the root causes of churn, assess risk levels, and provide actionable recommendations.

You must respond in the following JSON format:
{
    "summary": "Brief overall summary of the analysis (2-3 sentences)",
    "top_reasons": ["reason 1", "reason 2", "reason 3"],
    "risk_level": "high/medium/low",
    "actions": ["recommended action 1", "recommended action 2", "recommended action 3"],
    "citations": ["7590-VHVEG", "5575-GNVDE"]
}

Guidelines:
- Base your analysis ONLY on the provided customer data
- IMPORTANT: In citations, use ONLY the exact Customer ID format shown in the data (e.g., "7590-VHVEG"), NOT "customerID_xxx"
- Risk level should be based on the proportion of churned customers and severity of issues
- Actions should be specific and actionable
- Always respond in valid JSON format"""

USER_TEMPLATE = """Query: {query}

Relevant Customer Data:
{context}

Please analyze the above customer feedback and provide insights in the specified JSON format."""

print("Prompt templates defined ✓")

Prompt 模板定义完成 ✓


## 3.2 Implement RAG Pipeline

The RAG Pipeline is the core of the entire system, chaining the retrieval and generation steps together.

### Pipeline Steps

> Uses local Qwen2.5-7B-Instruct model, no API Key required, completely free

1. **Retrieve**: Use hybrid search to find Top-K relevant documents
2. **Build Context**: Format retrieved documents into LLM-readable text
3. **Generate**: Call the LLM API, passing in System Prompt, context, and user query
4. **Parse**: Parse the JSON response returned by the LLM

### Model Selection

We use **Qwen2.5-7B-Instruct** (4-bit quantized):
- Completely free, no API Key required
- Strong JSON structured output capability
- 128K context window, sufficient for processing 5 customer documents

### Temperature Parameter

`temperature=0.7` controls the randomness of output:
- `0`: Fully deterministic, same output every time
- `1`: More creative, but may be unstable
- `0.7`: Balance between accuracy and diversity

In [54]:
# --------------------------------------------
# 3.2 Implement RAG Pipeline
# ⚠️ Run on Google Colab (using local open-source model)
# --------------------------------------------

def build_context(search_results, max_docs=5):
    """
    Build LLM context
    """
    context_parts = []
    for idx, score in search_results[:max_docs]:
        doc = documents[idx]
        context_parts.append(f"--- Document (Relevance: {score:.4f}) ---\n{doc}\n")
    return "\n".join(context_parts)

def rag_query(user_query, k=5, max_new_tokens=1024):
    """
    RAG Query Pipeline (using local Qwen2.5-7B-Instruct)

    Args:
        user_query: User query
        k: Number of documents to retrieve
        max_new_tokens: Maximum tokens to generate

    Returns:
        dict: Parsed JSON result
    """
    # Step 1: Retrieve relevant documents
    search_results = hybrid_search(user_query, k=k)

    # Step 2: Build context
    context = build_context(search_results, max_docs=k)

    # Step 3: Build ChatML prompt and generate with local model
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_TEMPLATE.format(
            query=user_query,
            context=context
        )},
    ]

    text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
        )

    # Decode only the newly generated part
    generated_ids = outputs[0][inputs['input_ids'].shape[1]:]
    response_text = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    # Step 4: JSON parsing + regex fallback (open-source models may add text around JSON)
    try:
        result = json.loads(response_text)
    except json.JSONDecodeError:
        import re as _re
        json_match = _re.search(r'\{[\s\S]*\}', response_text)
        if json_match:
            try:
                result = json.loads(json_match.group())
            except json.JSONDecodeError:
                result = {"error": "Failed to parse JSON", "raw_response": response_text}
        else:
            result = {"error": "Failed to parse JSON", "raw_response": response_text}

    # Add retrieval metadata
    result["retrieved_docs"] = len(search_results)
    result["retrieved_customer_ids"] = [customer_ids[idx] for idx, _ in search_results]

    return result

print("RAG Pipeline defined ✓")
print("  Using model: Qwen2.5-7B-Instruct (local, 4-bit)")

RAG Pipeline 定义完成 ✓


## 3.3 Test RAG Pipeline

Use actual queries to test the complete RAG system and verify the end-to-end workflow.

In [57]:
# --------------------------------------------
# 3.3 Test RAG Pipeline
# --------------------------------------------

# Test query
test_queries = [
    "What are the main reasons customers are leaving due to internet service issues?",
    "Why are customers on month-to-month contracts churning?",
    "What do customers say about pricing and value for money?"
]

# Execute first test query
print("Testing RAG Pipeline")
print("=" * 50)
print(f"Query: {test_queries[0]}")
print("=" * 50)

result = rag_query(test_queries[0], k=5)

print("\nAnalysis Results:")
print(json.dumps(result, indent=2, ensure_ascii=False))

测试 RAG Pipeline
Query: What are the main reasons customers are leaving due to internet service issues?


RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

### Output Analysis

The RAG Pipeline successfully returned structured analysis results:

| Field | Content | Description |
|------|------|------|
| **summary** | Overall analysis summary | Summary generated by LLM based on retrieved documents |
| **top_reasons** | List of churn reasons | Key issues extracted from customer feedback |
| **risk_level** | high | Risk level determined based on data |
| **actions** | Recommended actions | Actionable improvement measures |
| **citations** | List of customer IDs | Data sources supporting the conclusions |

**Key Observations**:
- The LLM accurately extracted core reasons such as "unreliable internet service", "high prices", and "customer service issues" from the feedback
- All cited customer IDs come from the retrieval results, indicating the LLM followed the "analyze based on data" instruction
- The recommended actions are actionable

---

# Phase 4: Output & Evaluation

Phase 4 focuses on how to **present results** and **verify quality**.

## Importance of Evaluation

RAG system outputs need verification:
1. **Format Correctness**: Whether JSON is parseable
2. **Citation Accuracy**: Whether customer IDs cited by the LLM come from retrieval results
3. **Content Relevance**: Whether the analysis answers the user's question

## 4.1 Formatted Output

Convert JSON results into a human-readable report format.

In [26]:
# ============================================
# Phase 4: Output & Evaluation
# ============================================

# --------------------------------------------
# 4.1 Format Output Function
# --------------------------------------------

def display_analysis(result):
    """
    Display analysis results in formatted style
    """
    print("\n" + "=" * 60)
    print("📊 CUSTOMER CHURN ANALYSIS REPORT")
    print("=" * 60)
    
    if "error" in result:
        print(f"❌ Error: {result['error']}")
        return
    
    print(f"\n📝 Summary:")
    print(f"   {result.get('summary', 'N/A')}")
    
    print(f"\n🔍 Top Reasons for Churn:")
    for i, reason in enumerate(result.get('top_reasons', []), 1):
        print(f"   {i}. {reason}")
    
    print(f"\n⚠️ Risk Level: {result.get('risk_level', 'N/A').upper()}")
    
    print(f"\n💡 Recommended Actions:")
    for i, action in enumerate(result.get('actions', []), 1):
        print(f"   {i}. {action}")
    
    print(f"\n📎 Citations (Customer IDs):")
    print(f"   {', '.join(result.get('citations', []))}")
    
    print(f"\n📚 Retrieved Documents: {result.get('retrieved_docs', 0)}")
    print("=" * 60)

# Test formatted output
display_analysis(result)


📊 CUSTOMER CHURN ANALYSIS REPORT

📝 Summary:
   The analysis of customer feedback reveals that the primary reasons for churn are related to inadequate internet service availability, high pricing, and poor customer service experiences. Customers express dissatisfaction with billing issues and payment methods, which further exacerbate their frustrations leading to their decision to leave.

🔍 Top Reasons for Churn:
   1. Lack of internet service availability in certain areas
   2. High pricing for internet services
   3. Poor customer service and billing issues

⚠️ Risk Level: HIGH

💡 Recommended Actions:
   1. Expand internet service availability in underserved areas to attract and retain customers.
   2. Review and adjust pricing strategies to ensure competitiveness and perceived value.
   3. Enhance customer service training and streamline billing processes to improve customer satisfaction.

📎 Citations (Customer IDs):
   4877-EVATK, 1871-MOWRM, 5687-DKDTV, 6892-EZDTG, 8065-YKXKD

📚 R

## 4.2 Citation Validation

### What Is Citation Validation?

Citation validation checks whether the customer IDs cited by the LLM **actually exist in the retrieval results**.

This is an important measure to prevent **LLM Hallucination**. Hallucination refers to the LLM generating information that appears plausible but actually does not exist.

### Validation Logic

```mermaid
%%{init: {'theme': 'dark', 'themeVariables': { 'fontSize': '13px'}}}%%
flowchart LR
    A["LLM Output<br/>citations"] --> B{"Validation"}
    C["Retrieved<br/>customer_ids"] --> B
    B --> D["Calculate<br/>Accuracy"]

    style A fill:#4a1942,stroke:#ff6b9d,color:#fff
    style B fill:#1a1a2e,stroke:#ffd700,color:#fff
    style C fill:#2d4a3e,stroke:#00ff88,color:#fff
    style D fill:#3d1a4a,stroke:#bf7fff,color:#fff
```

### Why Is ID Normalization Needed?

The LLM may return IDs in different formats:
- `7590-VHVEG` (correct)
- `customerID_7590-VHVEG` (added prefix)
- `7590-vhveg` (different case)

Our `normalize_customer_id` function handles these variants to ensure validation robustness.

In [ ]:
# --------------------------------------------
# 4.2 Citation Validation
# --------------------------------------------

def normalize_customer_id(cid):
    """
    Normalize customer ID, handle various formats
    """
    cid = cid.strip().lower()
    # Remove possible prefixes
    prefixes = ['customerid_', 'customer_id_', 'cid_', 'id_']
    for prefix in prefixes:
        if cid.startswith(prefix):
            cid = cid[len(prefix):]
    return cid

def validate_citations(result):
    """
    Validate whether cited customer IDs are in retrieved results
    """
    citations = result.get('citations', [])
    retrieved_ids = result.get('retrieved_customer_ids', [])
    
    # Normalize all IDs
    retrieved_normalized = {normalize_customer_id(rid): rid for rid in retrieved_ids}
    
    valid_citations = []
    invalid_citations = []
    
    for cid in citations:
        normalized = normalize_customer_id(cid)
        if normalized in retrieved_normalized:
            valid_citations.append(cid)
        else:
            invalid_citations.append(cid)
    
    accuracy = len(valid_citations) / len(citations) if citations else 0
    
    return {
        "total_citations": len(citations),
        "valid_citations": valid_citations,
        "invalid_citations": invalid_citations,
        "accuracy": accuracy
    }

# Validation result
validation = validate_citations(result)
print("Citation Validation Results:")
print(f"  Total citations: {validation['total_citations']}")
print(f"  Valid citations: {validation['valid_citations']}")
print(f"  Invalid citations: {validation['invalid_citations']}")
print(f"  Citation accuracy: {validation['accuracy']*100:.1f}%")

引用验证结果:
  总引用数: 5
  有效引用: ['4877-EVATK', '1871-MOWRM', '5687-DKDTV', '6892-EZDTG', '8065-YKXKD']
  无效引用: []
  引用准确率: 100.0%


### Output Analysis

Citation validation results show **100% accuracy**, all citations are valid. This indicates:
1. Prompt design is effective, the LLM followed the "only cite provided data" instruction
2. The system did not produce hallucinations

**If accuracy is below 100%**, you may need to:
- Adjust the Prompt to emphasize citation constraints
- Check retrieval quality to ensure relevant documents are retrieved
- Consider using a larger open-source model (e.g., Qwen2.5-14B)

## 4.3 Interactive Analysis Interface

Encapsulate the complete analysis workflow and provide a concise calling interface.

In [28]:
# --------------------------------------------
# 4.3 Interactive Analysis Interface
# --------------------------------------------

def analyze_churn(query):
    """
    Complete churn analysis function
    
    Args:
        query: Analysis query
    
    Returns:
        Analysis result
    """
    print(f"🔎 Analyzing: {query}")
    print("-" * 50)
    
    # Execute RAG query
    result = rag_query(query, k=5)
    
    # Display results
    display_analysis(result)
    
    # Validate citations
    validation = validate_citations(result)
    print(f"\n✅ Citation Accuracy: {validation['accuracy']*100:.1f}%")
    
    return result

# Example queries
print("=" * 60)
print("🎉 Customer Churn Insight Tool Ready!")
print("=" * 60)
print("\nUsage: result = analyze_churn('your query here')")
print("\nExample queries:")
print("  1. 'Why are customers with fiber optic internet churning?'")
print("  2. 'What issues do senior citizens have with our service?'")
print("  3. 'What are the common complaints about customer support?'")

🎉 Customer Churn Insight Tool Ready!

使用方法: result = analyze_churn('your query here')

示例查询:
  1. 'Why are customers with fiber optic internet churning?'
  2. 'What issues do senior citizens have with our service?'
  3. 'What are the common complaints about customer support?'


## 4.4 Full Example

Run a complete analysis query to demonstrate the system's end-to-end capability.

In [29]:
# --------------------------------------------
# Example: Run full analysis
# --------------------------------------------

# Uncomment to run analysis
result = analyze_churn("Why are customers with fiber optic internet churning?")

🔎 Analyzing: Why are customers with fiber optic internet churning?
--------------------------------------------------

📊 CUSTOMER CHURN ANALYSIS REPORT

📝 Summary:
   The analysis indicates that customers with fiber optic internet are primarily churning due to service disruptions and inconsistent speeds. While some customers appreciate the initial pricing, the overall dissatisfaction with reliability and customer support significantly contributes to their decision to leave.

🔍 Top Reasons for Churn:
   1. Frequent service disruptions
   2. Inconsistent internet speeds
   3. Poor customer support

⚠️ Risk Level: HIGH

💡 Recommended Actions:
   1. Enhance service reliability through infrastructure improvements
   2. Implement a proactive customer support system with quicker response times
   3. Gather customer feedback regularly to address service issues promptly

📎 Citations (Customer IDs):
   6680-WKXRZ, 8065-YKXKD

📚 Retrieved Documents: 5

✅ Citation Accuracy: 100.0%


### Output Analysis

The complete analysis workflow executed successfully:
1. Retrieved relevant customer data
2. LLM generated a structured analysis report
3. Citation validation passed (100% accuracy)

The analysis revealed the main reasons for fiber optic customer churn: frequent service interruptions, unstable speeds, and insufficient customer support.

---

# Conclusion

## Technology Stack Review

| Component | Technology | Purpose |
|------|------|------|
| Data Processing | Pandas | Load, clean, transform data |
| Text Embedding | Sentence-Transformers (BGE) | Convert text to 768-dimensional vectors |
| Vector Search | FAISS | Efficient similarity search |
| Keyword Search | BM25 | Exact keyword matching |
| Result Fusion | RRF | Merge hybrid search rankings |
| Text Generation | Qwen2.5-7B-Instruct (4-bit) | Analysis and reasoning |
| Output Format | JSON | Structured, parseable output |

## System Features

1. **Traceability**: All analytical conclusions are supported by customer ID citations
2. **Accuracy**: Hybrid search + citation validation ensures data accuracy
3. **Scalability**: Easily scalable to larger datasets (using approximate indexes)
4. **Interpretability**: Structured output, easy to understand and use

## Future Improvements

1. **Retrieval Optimization**:
   - Add a Reranker (e.g., cross-encoder) to further improve precision
   - Try different embedding models (e.g., bge-large-en-v1.5)

2. **LLM Optimization**:
   - Use QLoRA fine-tuning to improve output quality (see Phase 5-8)
   - Implement multi-turn conversation, support follow-up questions

3. **Evaluation Framework**:
   - Build annotated datasets for quantitative evaluation
   - Implement A/B testing framework

4. **Production Deployment**:
   - Persist vector indexes (save/load FAISS indexes)
   - Add API interface (FastAPI/Flask)
   - Implement caching mechanism

## Usage Examples

```python
# Analyze customer churn causes
result = analyze_churn("Why are customers with fiber optic internet churning?")

# Analyze specific groups
result = analyze_churn("What issues do senior citizens have with our service?")

# Analyze service issues
result = analyze_churn("What are the common complaints about customer support?")

# Analyze price sensitivity
result = analyze_churn("Are customers leaving because of high prices?")
```

## Phase 3-4 Model Cleanup

Before starting Phase 5 (loading the 14B teacher model), we need to release the GPU memory used by the 7B model from Phase 3-4.

- 7B model uses ~4.5 GB VRAM
- 14B teacher model needs ~8 GB VRAM
- T4 has 15 GB total, need to release 7B before loading 14B

In [ ]:
# --------------------------------------------
# Release GPU memory from Phase 3-4 model
# (Free up space for Phase 5's 14B teacher model)
# ⚠️ Run on Google Colab
# --------------------------------------------

import gc

print(f"GPU memory before release: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")

# Release the 7B model loaded in Phase 3
if 'model' in dir() and model is not None:
    del model
if 'tokenizer' in dir() and tokenizer is not None:
    del tokenizer

gc.collect()
torch.cuda.empty_cache()

print(f"GPU memory after release: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")
print("\n7B model released, ready to load 14B teacher model ✓")

---

# Phase 5: Training Data Generation

> **Warning: Starting from Phase 5, all code runs on Google Colab (free T4 GPU)**

## Objective

Use **Qwen2.5-14B-Instruct** (4-bit quantized) as the teacher model to generate high-quality JSON-formatted training data for each query, which will be used to fine-tune the 7B student model.

## Strategy

| Step | Description |
|------|------|
| 5.0 | Colab environment setup + rebuild retrieval system |
| 5.1 | Design 8 query template categories, generate ~60-80 unique queries |
| 5.2 | Use 14B teacher model to generate Gold Standard training data |
| 5.3 | Data augmentation (k=3,5,7 multi-round generation) |
| 5.4 | Train/validation split (85%/15%) |
| 5.5 | Export ChatML format JSONL |
| 5.6 | Release teacher model memory |

### VRAM Estimate

- BGE embedding model: ~0.5 GB
- Qwen2.5-14B-Instruct (4-bit): ~8 GB
- **Total: ~8.5 GB - Safe for T4 (15 GB limit)**

## 5.0 Colab Environment Setup

Install all dependencies on Colab and rebuild the retrieval system. Since Colab is a fresh environment, data needs to be reloaded and indexes rebuilt.

**New dependencies installed**:
- `peft`: LoRA adapter framework
- `bitsandbytes`: 4-bit / 8-bit quantization support
- `trl`: Transformer Reinforcement Learning, provides `SFTTrainer`
- `datasets`: Hugging Face dataset loading
- `accelerate`: Distributed training and mixed precision support

In [ ]:
# ============================================
# Phase 5: Training Data Generation
# ⚠️ Run on Google Colab (T4 GPU)
# ============================================

# --------------------------------------------
# 5.0 Colab Environment Setup
# --------------------------------------------

# Install dependencies
!pip install -q transformers peft bitsandbytes trl datasets accelerate
!pip install -q sentence-transformers faiss-cpu rank_bm25

# Mount Google Drive (for saving model adapter later)
from google.colab import drive
drive.mount('/content/drive')

import os
import torch

# Check GPU availability
print(f"GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU model: {torch.cuda.get_device_name(0)}")
    print(f"GPU memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")

print("\nEnvironment setup complete ✓")

### Upload Data and Rebuild Retrieval System

Reuse Phase 1-2 logic: Load CSV -> Create customer documents -> Build FAISS + BM25 indexes.

**Note**: Please upload `telco_churn_with_all_feedback.csv` to Colab first, or place it in Google Drive.

In [ ]:
# --------------------------------------------
# 5.0b Load Data + Rebuild Retrieval System
# [Optional] Skip if Phase 1-2 variables are still in memory
# (Reuse Phase 1-2 logic)
# ⚠️ Run on Google Colab
# --------------------------------------------

import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings('ignore')

# === Load Data ===
# Method 1: Upload from Colab
# from google.colab import files
# uploaded = files.upload()

# Method 2: Read from Google Drive (recommended)
DATA_PATH = '/content/drive/MyDrive/telco_churn_with_all_feedback.csv'

# If not in Drive, try current directory
if not os.path.exists(DATA_PATH):
    DATA_PATH = '/content/telco_churn_with_all_feedback.csv'
    if not os.path.exists(DATA_PATH):
        from google.colab import files
        print("Please upload telco_churn_with_all_feedback.csv:")
        uploaded = files.upload()
        DATA_PATH = list(uploaded.keys())[0]

df_main = pd.read_csv(DATA_PATH)
print(f"Data loaded: {df_main.shape}")

# === Data Preprocessing (same as Phase 1) ===
df = df_main.copy()
if 'PromptInput' in df.columns:
    df = df.drop(columns=['PromptInput'])
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(df['MonthlyCharges'])
df['Churn_Binary'] = (df['Churn'] == 'Yes').astype(int)

# Check feedback field
df['has_feedback'] = df['CustomerFeedback'].notna() & (df['CustomerFeedback'].str.len() > 10)

# === Create Customer Documents (same as Phase 1.7) ===
def create_customer_document(row):
    doc = f"""Customer ID: {row['customerID']}
Churn Status: {row['Churn']}

Customer Profile:
- Gender: {row['gender']}
- Senior Citizen: {'Yes' if row['SeniorCitizen'] == 1 else 'No'}
- Partner: {row['Partner']}
- Dependents: {row['Dependents']}
- Tenure: {row['tenure']} months

Services:
- Phone Service: {row['PhoneService']}
- Internet Service: {row['InternetService']}
- Online Security: {row['OnlineSecurity']}
- Tech Support: {row['TechSupport']}
- Streaming TV: {row['StreamingTV']}
- Streaming Movies: {row['StreamingMovies']}

Contract & Billing:
- Contract: {row['Contract']}
- Monthly Charges: ${row['MonthlyCharges']}
- Total Charges: ${row['TotalCharges']:.2f}
- Payment Method: {row['PaymentMethod']}

Customer Feedback:
{row['CustomerFeedback']}
"""
    return doc

df_with_feedback = df[df['has_feedback']].copy()
df_with_feedback['document'] = df_with_feedback.apply(create_customer_document, axis=1)

def preprocess_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    return text

documents = df_with_feedback['document'].apply(preprocess_text).tolist()
customer_ids = df_with_feedback['customerID'].tolist()

# === Build Retrieval System (same as Phase 2) ===
from sentence_transformers import SentenceTransformer
import faiss
from rank_bm25 import BM25Okapi

print("Loading BGE embedding model...")
embedding_model = SentenceTransformer('BAAI/bge-base-en-v1.5')

print("Generating document embeddings...")
document_embeddings = embedding_model.encode(
    documents, show_progress_bar=True, normalize_embeddings=True
)

# FAISS index
dimension = document_embeddings.shape[1]
faiss_index = faiss.IndexFlatIP(dimension)
faiss_index.add(document_embeddings.astype('float32'))

# BM25 index
tokenized_docs = [doc.lower().split() for doc in documents]
bm25_index = BM25Okapi(tokenized_docs)

# Retrieval functions (same as Phase 2.5)
def vector_search(query, k=10):
    query_embedding = embedding_model.encode([query], normalize_embeddings=True)
    scores, indices = faiss_index.search(query_embedding.astype('float32'), k)
    return list(zip(indices[0], scores[0]))

def bm25_search(query, k=10):
    tokenized_query = query.lower().split()
    scores = bm25_index.get_scores(tokenized_query)
    top_indices = np.argsort(scores)[::-1][:k]
    return [(idx, scores[idx]) for idx in top_indices]

def hybrid_search(query, k=10, alpha=0.5):
    vector_results = vector_search(query, k=k*2)
    bm25_results = bm25_search(query, k=k*2)
    rrf_scores = {}
    rrf_k = 60
    for rank, (idx, _) in enumerate(vector_results):
        rrf_scores[idx] = rrf_scores.get(idx, 0) + alpha / (rrf_k + rank + 1)
    for rank, (idx, _) in enumerate(bm25_results):
        rrf_scores[idx] = rrf_scores.get(idx, 0) + (1 - alpha) / (rrf_k + rank + 1)
    sorted_results = sorted(rrf_scores.items(), key=lambda x: x[1], reverse=True)[:k]
    return sorted_results

def build_context(search_results, max_docs=5):
    context_parts = []
    for idx, score in search_results[:max_docs]:
        doc = documents[idx]
        context_parts.append(f"--- Document (Relevance: {score:.4f}) ---\n{doc}\n")
    return "\n".join(context_parts)

# Prompt template (same as Phase 3.1)
SYSTEM_PROMPT = """You are a customer churn analysis expert. Based on the provided customer feedback and profile data, analyze the root causes of churn, assess risk levels, and provide actionable recommendations.

You must respond in the following JSON format:
{
    "summary": "Brief overall summary of the analysis (2-3 sentences)",
    "top_reasons": ["reason 1", "reason 2", "reason 3"],
    "risk_level": "high/medium/low",
    "actions": ["recommended action 1", "recommended action 2", "recommended action 3"],
    "citations": ["7590-VHVEG", "5575-GNVDE"]
}

Guidelines:
- Base your analysis ONLY on the provided customer data
- IMPORTANT: In citations, use ONLY the exact Customer ID format shown in the data (e.g., "7590-VHVEG"), NOT "customerID_xxx"
- Risk level should be based on the proportion of churned customers and severity of issues
- Actions should be specific and actionable
- Always respond in valid JSON format"""

USER_TEMPLATE = """Query: {query}

Relevant Customer Data:
{context}

Please analyze the above customer feedback and provide insights in the specified JSON format."""

print(f"\nRetrieval system rebuilt:")
print(f"  Documents: {len(documents)}")
print(f"  FAISS index: {faiss_index.ntotal} vectors ({dimension}D)")
print(f"  BM25 vocabulary: {len(bm25_index.idf)} words")
print("✓ Phase 5.0 complete")

## 5.1 Design Query Templates

We design **8 categories of query templates** covering different analysis dimensions:

| Category | Description | Example |
|------|------|------|
| Service Issues | Churn analysis related to specific services | "Why are fiber optic customers churning?" |
| Demographics | Characteristics of different customer groups | "What issues do senior citizens face?" |
| Contract Type | Relationship between contracts and churn | "Why do month-to-month customers leave?" |
| Tenure | Churn patterns by tenure | "What are the concerns of new customers?" |
| Sentiment | Customer emotion-related queries | "What are the most negative feedback themes?" |
| Pricing | Price sensitivity analysis | "How does pricing affect customer retention?" |
| Comparison | Comparisons between groups | "Compare churn between DSL and fiber optic users" |
| Action | Decision-oriented queries | "What should we do to reduce churn?" |

Through parameter substitution (service names, customer groups, etc.), each category generates 8-10 queries, totaling ~60-80 unique queries.

In [ ]:
# --------------------------------------------
# 5.1 Design Query Templates
# ⚠️ Run on Google Colab
# --------------------------------------------

import random
random.seed(42)

# 8 categories of query templates
query_templates = {
    "service": [
        "Why are customers with {service} churning?",
        "What are the main complaints about {service}?",
        "How does {service} quality affect customer retention?",
        "What feedback do churned customers give about {service}?",
    ],
    "demographics": [
        "What issues do {group} face with our services?",
        "Why are {group} more likely to churn?",
        "What are the common complaints from {group}?",
        "How can we improve retention for {group}?",
    ],
    "contract": [
        "Why do {contract} contract customers leave?",
        "What are the churn patterns for {contract} contracts?",
        "How does {contract} contract type affect customer satisfaction?",
    ],
    "tenure": [
        "What are the concerns of customers with {tenure} tenure?",
        "Why do customers with {tenure} tenure churn?",
        "What feedback patterns exist for {tenure} tenure customers?",
    ],
    "sentiment": [
        "What are the most negative feedback themes?",
        "What do unhappy customers complain about most?",
        "What are the key drivers of customer dissatisfaction?",
        "What emotional patterns appear in churned customer feedback?",
        "Which service issues generate the strongest negative reactions?",
    ],
    "pricing": [
        "How does pricing affect customer retention?",
        "What do customers say about value for money?",
        "Are high-paying customers more likely to churn?",
        "What pricing-related complaints lead to churn?",
        "How do monthly charges relate to customer satisfaction?",
    ],
    "comparison": [
        "Compare churn between {comp_a} and {comp_b} customers",
        "What differences exist between {comp_a} and {comp_b} customer feedback?",
        "Which group has higher churn risk: {comp_a} or {comp_b}?",
    ],
    "action": [
        "What should we do to reduce churn among {target} customers?",
        "What retention strategies would work for {target} customers?",
        "What immediate actions can prevent {target} customers from leaving?",
        "How can we improve the experience for {target} customers?",
    ],
}

# Parameter sets
params = {
    "service": ["fiber optic internet", "DSL internet", "phone service",
                 "online security", "tech support", "streaming TV", "streaming movies"],
    "group": ["senior citizens", "customers without partners",
              "customers with dependents", "young customers", "female customers"],
    "contract": ["month-to-month", "one year", "two year"],
    "tenure": ["less than 6 months", "6-12 months", "1-2 years",
               "2-4 years", "over 5 years"],
    "comp_a": ["DSL", "month-to-month", "senior citizen", "male"],
    "comp_b": ["fiber optic", "two-year contract", "non-senior", "female"],
    "target": ["high-value", "month-to-month", "fiber optic", "new",
               "senior citizen", "long-tenure", "price-sensitive"],
}

# Generate all queries
all_queries = []

for category, templates in query_templates.items():
    for template in templates:
        if "{service}" in template:
            for svc in params["service"]:
                all_queries.append({"query": template.format(service=svc), "category": category})
        elif "{group}" in template:
            for grp in params["group"]:
                all_queries.append({"query": template.format(group=grp), "category": category})
        elif "{contract}" in template:
            for ct in params["contract"]:
                all_queries.append({"query": template.format(contract=ct), "category": category})
        elif "{tenure}" in template:
            for tn in params["tenure"]:
                all_queries.append({"query": template.format(tenure=tn), "category": category})
        elif "{comp_a}" in template:
            for a, b in zip(params["comp_a"], params["comp_b"]):
                all_queries.append({"query": template.format(comp_a=a, comp_b=b), "category": category})
        elif "{target}" in template:
            for tgt in params["target"]:
                all_queries.append({"query": template.format(target=tgt), "category": category})
        else:
            all_queries.append({"query": template, "category": category})

# Deduplicate
seen = set()
unique_queries = []
for q in all_queries:
    if q["query"] not in seen:
        seen.add(q["query"])
        unique_queries.append(q)

print(f"Total queries generated: {len(unique_queries)}")
print(f"\nQueries per category:")
from collections import Counter
cat_counts = Counter(q["category"] for q in unique_queries)
for cat, count in sorted(cat_counts.items()):
    print(f"  {cat}: {count}")
print(f"\nExample queries:")
for q in unique_queries[:5]:
    print(f"  [{q['category']}] {q['query']}")

## 5.2 Load Teacher Model to Generate Gold Standard Training Data

### Teacher Model Selection: Qwen2.5-14B-Instruct

| Attribute | Description |
|------|------|
| Model | `Qwen/Qwen2.5-14B-Instruct` |
| Quantization | 4-bit (NF4 + double quantization) |
| VRAM | ~8 GB |
| Advantage | Strong JSON structured output capability, excellent in both Chinese and English |
| License | Apache 2.0 |

### Generation Process

For each query:
1. Call `hybrid_search()` to get Top-K documents
2. Build prompt with `SYSTEM_PROMPT` + `USER_TEMPLATE`
3. Use 14B teacher model for inference to generate JSON response
4. Validate JSON contains all 5 required fields (summary, top_reasons, risk_level, actions, citations)

In [ ]:
# --------------------------------------------
# 5.2 Load Teacher Model (Qwen2.5-14B-Instruct 4-bit)
# ⚠️ Run on Google Colab
# --------------------------------------------

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import json
import gc

# 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",             # NF4 quantization (information-theoretically optimal)
    bnb_4bit_compute_dtype=torch.bfloat16,  # Use bfloat16 for computation
    bnb_4bit_use_double_quant=True,         # Double quantization, further compression
)

TEACHER_MODEL_NAME = "Qwen/Qwen2.5-14B-Instruct"

print(f"Loading teacher model: {TEACHER_MODEL_NAME} (4-bit)...")
print("Estimated time: 3-5 minutes...")

teacher_tokenizer = AutoTokenizer.from_pretrained(
    TEACHER_MODEL_NAME,
    trust_remote_code=True
)

teacher_model = AutoModelForCausalLM.from_pretrained(
    TEACHER_MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
teacher_model.eval()

# Check memory usage
print(f"\nTeacher model loaded ✓")
print(f"GPU memory usage: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")
print(f"GPU total memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")

### Generate Training Data with Teacher Model

For each query, use the teacher model to generate structured JSON responses with strict format validation.

**Validation Rules**:
- Must be valid JSON
- Must contain 5 fields: `summary`, `top_reasons`, `risk_level`, `actions`, `citations`
- `risk_level` must be one of `high`/`medium`/`low`
- All list fields must be non-empty

In [ ]:
# --------------------------------------------
# 5.2b Generate Training Data with Teacher Model
# ⚠️ Run on Google Colab
# --------------------------------------------

def generate_with_teacher(query, k=5, max_new_tokens=1024):
    """
    Generate RAG response using teacher model

    Args:
        query: User query
        k: Number of documents to retrieve
        max_new_tokens: Maximum tokens to generate

    Returns:
        dict: Parsed JSON result, returns None on failure
    """
    # Step 1-2: Retrieve + build context (same as original rag_query)
    search_results = hybrid_search(query, k=k)
    context = build_context(search_results, max_docs=k)

    # Step 3: Build ChatML format messages
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_TEMPLATE.format(query=query, context=context)},
    ]

    # Use tokenizer's chat template
    text = teacher_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = teacher_tokenizer(text, return_tensors="pt").to(teacher_model.device)

    # Generate
    with torch.no_grad():
        outputs = teacher_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=teacher_tokenizer.eos_token_id,
        )

    # Decode (only the newly generated part)
    generated_ids = outputs[0][inputs['input_ids'].shape[1]:]
    response_text = teacher_tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    # Step 4: Parse JSON
    try:
        # Try direct parsing
        result = json.loads(response_text)
    except json.JSONDecodeError:
        # Try extracting JSON block (model may add text around JSON)
        import re
        json_match = re.search(r'\{[\s\S]*\}', response_text)
        if json_match:
            try:
                result = json.loads(json_match.group())
            except json.JSONDecodeError:
                return None
        else:
            return None

    # Validate required fields
    required_fields = ['summary', 'top_reasons', 'risk_level', 'actions', 'citations']
    if not all(field in result for field in required_fields):
        return None

    # Validate field types and values
    if not isinstance(result['top_reasons'], list) or len(result['top_reasons']) == 0:
        return None
    if result['risk_level'] not in ['high', 'medium', 'low']:
        return None
    if not isinstance(result['actions'], list) or len(result['actions']) == 0:
        return None
    if not isinstance(result['citations'], list):
        return None

    # Add retrieval metadata
    result['retrieved_customer_ids'] = [customer_ids[idx] for idx, _ in search_results]

    return result

# Test teacher model generation
print("Testing teacher model generation...")
test_result = generate_with_teacher("Why are fiber optic customers churning?", k=5)
if test_result:
    print("✓ Teacher model generation test passed")
    print(f"  summary: {test_result['summary'][:80]}...")
    print(f"  risk_level: {test_result['risk_level']}")
    print(f"  top_reasons: {len(test_result['top_reasons'])} items")
    print(f"  actions: {len(test_result['actions'])} items")
    print(f"  citations: {test_result['citations']}")
else:
    print("✗ Teacher model generation test failed, please check model output")

## 5.3 Data Augmentation

For each query, generate training data using **k=3, 5, 7** (number of retrieved documents), totaling approximately **180-240 samples**.

Significance of different k values:
- **k=3**: Few highly relevant documents -> Model learns precise analysis
- **k=5**: Standard retrieval amount -> Consistent with inference time
- **k=7**: More context -> Model learns to handle noisy information

## 5.4 Train/Validation Split

Use **85%/15%** stratified split, stratified by query category to ensure uniform distribution across categories.

## 5.5 Export ChatML Format

Use Qwen2.5's ChatML template format, each data sample contains a complete system + user + assistant three-turn conversation.

In [ ]:
# --------------------------------------------
# 5.3 Data Augmentation + 5.4 Split + 5.5 Export
# ⚠️ Run on Google Colab
# --------------------------------------------

from tqdm import tqdm

# === 5.3 Data Augmentation: Multi-k Generation ===
training_samples = []
failed_count = 0
k_values = [3, 5, 7]

print("Starting training data generation...")
print(f"Number of queries: {len(unique_queries)}, k values: {k_values}")
print(f"Expected to generate: {len(unique_queries) * len(k_values)} samples")
print("=" * 50)

for k in k_values:
    print(f"\n--- Generating with k={k} ---")
    for i, q_info in enumerate(tqdm(unique_queries, desc=f"k={k}")):
        query = q_info["query"]
        category = q_info["category"]

        result = generate_with_teacher(query, k=k)

        if result is not None:
            # Build context (same as during generation)
            search_results = hybrid_search(query, k=k)
            context = build_context(search_results, max_docs=k)

            # Build training sample
            sample = {
                "query": query,
                "category": category,
                "k": k,
                "context": context,
                "response": json.dumps(result, ensure_ascii=False),
            }
            training_samples.append(sample)
        else:
            failed_count += 1

        # Clear GPU cache every 20 samples
        if (i + 1) % 20 == 0:
            torch.cuda.empty_cache()

print(f"\nGeneration complete:")
print(f"  Succeeded: {len(training_samples)} items")
print(f"  Failed: {failed_count} items")
print(f"  Success rate: {len(training_samples)/(len(training_samples)+failed_count)*100:.1f}%")

# === 5.4 Train/Validation Split (85%/15%, stratified by category) ===
from sklearn.model_selection import train_test_split

# Stratified split by category
categories = [s["category"] for s in training_samples]
train_samples, val_samples = train_test_split(
    training_samples, test_size=0.15, random_state=42, stratify=categories
)

print(f"\nData split:")
print(f"  Training set: {len(train_samples)} items")
print(f"  Validation set: {len(val_samples)} items")

# === 5.5 Export ChatML Format JSONL ===
def to_chatml(sample):
    """Convert sample to Qwen2.5 ChatML format"""
    user_content = USER_TEMPLATE.format(
        query=sample["query"],
        context=sample["context"]
    )
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
        {"role": "assistant", "content": sample["response"]},
    ]

    # Use tokenizer's chat template to generate full text
    text = teacher_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=False
    )

    return {"text": text, "messages": messages}

# Export to JSONL
os.makedirs("data", exist_ok=True)

train_path = "data/finetune_train_hf.jsonl"
val_path = "data/finetune_val_hf.jsonl"

with open(train_path, 'w', encoding='utf-8') as f:
    for sample in train_samples:
        chatml = to_chatml(sample)
        f.write(json.dumps(chatml, ensure_ascii=False) + '\n')

with open(val_path, 'w', encoding='utf-8') as f:
    for sample in val_samples:
        chatml = to_chatml(sample)
        f.write(json.dumps(chatml, ensure_ascii=False) + '\n')

print(f"\nExport complete:")
print(f"  Training set: {train_path} ({len(train_samples)} items)")
print(f"  Validation set: {val_path} ({len(val_samples)} items)")

# Verify exported file
with open(train_path, 'r') as f:
    first_line = json.loads(f.readline())
    print(f"\nSample verification:")
    print(f"  Fields: {list(first_line.keys())}")
    print(f"  text length: {len(first_line['text'])} characters")
    print(f"  messages count: {len(first_line['messages'])} turns")

# Also save to Google Drive
drive_data_dir = '/content/drive/MyDrive/lora_finetune_data'
os.makedirs(drive_data_dir, exist_ok=True)
import shutil
shutil.copy(train_path, os.path.join(drive_data_dir, 'finetune_train_hf.jsonl'))
shutil.copy(val_path, os.path.join(drive_data_dir, 'finetune_val_hf.jsonl'))
print(f"\nBacked up to Google Drive: {drive_data_dir}")
print("\n✓ Phase 5.3-5.5 complete")

## 5.6 Release Teacher Model Memory

The 14B teacher model uses approximately 8GB of VRAM, which needs to be released before loading the 7B student model for fine-tuning.

Use `del model` + `torch.cuda.empty_cache()` + `gc.collect()` triple cleanup to ensure complete memory release.

In [ ]:
# --------------------------------------------
# 5.6 Release Teacher Model Memory
# ⚠️ Run on Google Colab
# --------------------------------------------

print(f"GPU memory before release: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")

# Delete teacher model and tokenizer
del teacher_model
del teacher_tokenizer
gc.collect()
torch.cuda.empty_cache()

print(f"GPU memory after release: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")
print("\n✓ Phase 5 complete - Teacher model memory released")
print("  Training data saved, ready to start Phase 6 fine-tuning")

---

# Phase 6: QLoRA Fine-tuning

> **Warning: Run on Google Colab (free T4 GPU)**

## Objective

Use **QLoRA** to fine-tune **Qwen2.5-7B-Instruct** to generate high-quality structured JSON responses for the customer churn analysis task.

## Base Model: Qwen2.5-7B-Instruct

| Attribute | Description |
|------|------|
| Parameters | 7.6B |
| Size after quantization | ~4.5 GB (4-bit) |
| Training peak VRAM | ~12 GB |
| T4 safe | Yes (within 15 GB limit) |
| License | Apache 2.0 |

## What Is QLoRA?

**QLoRA (Quantized Low-Rank Adaptation)** combines two key techniques:

1. **4-bit Quantization**: Compresses model weights from FP16 (2 bytes) to 4-bit (0.5 bytes), reducing memory usage by 75%
2. **LoRA Low-Rank Adaptation**: Freezes original weights, only trains a small number of low-rank matrices (~20M parameters, 0.26% of total)

### LoRA Parameter Explanation

| Parameter | Value | Description |
|------|-----|------|
| `r` | 16 | Rank of low-rank matrices; higher means more expressive but uses more memory |
| `lora_alpha` | 32 | Scaling factor, typically set to 2r |
| `lora_dropout` | 0.05 | Dropout to prevent overfitting |
| Target modules | q/k/v/o/gate/up/down_proj | Covers all attention + FFN layers |

### Training Parameter Explanation

| Parameter | Value | Description |
|------|-----|------|
| Epochs | 3 | Train more rounds for small datasets |
| Batch size | 1 | Limited by VRAM |
| Gradient accumulation | 8 | Effective batch size = 8 |
| Learning rate | 2e-4 | QLoRA standard learning rate |
| Optimizer | paged_adamw_8bit | 8-bit optimizer to save memory |
| Scheduler | cosine | Cosine annealing for stable training |
| Max sequence length | 2048 | Covers RAG context + response |

In [ ]:
# ============================================
# Phase 6: QLoRA Fine-tuning
# ⚠️ Run on Google Colab (T4 GPU)
# ============================================

# --------------------------------------------
# 6.1 Load Base Model + Configure QLoRA
# --------------------------------------------

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
import torch

# 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,  # A100 natively supports bfloat16
    bnb_4bit_use_double_quant=True,
)

BASE_MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"

print(f"Loading base model: {BASE_MODEL_NAME} (4-bit)...")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
tokenizer.model_max_length = 2048       # Limit max sequence length

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)

# Prepare model for k-bit training
model = prepare_model_for_kbit_training(model)

# Configure LoRA adapter
lora_config = LoraConfig(
    r=16,                           # Rank of low-rank matrices
    lora_alpha=32,                  # Scaling factor (usually = 2r)
    lora_dropout=0.05,              # Dropout to prevent overfitting
    bias="none",                    # Do not train bias
    task_type="CAUSAL_LM",         # Causal language model task
    target_modules=[                # Target modules: cover all linear layers
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
)

# Apply LoRA
model = get_peft_model(model, lora_config)

# Print trainable parameters
model.print_trainable_parameters()

print(f"\nGPU memory usage: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")
print("\n✓ Model loading and LoRA configuration complete")

### Load Training Data and Start Training

Use `SFTTrainer` (Supervised Fine-Tuning Trainer) for training. It wraps the Hugging Face Trainer with optimizations for instruction fine-tuning scenarios.

**Training Estimate**:
- ~180-240 samples, 3 epochs
- Batch size 1 x Gradient accumulation 8 = effective batch 8
- Estimated training time: **~30-50 minutes** (T4 GPU)

In [ ]:
# --------------------------------------------
# 6.2 Load Training Data + SFTTrainer Training
# ⚠️ Run on Google Colab
# --------------------------------------------

from datasets import load_dataset
from trl import SFTTrainer, SFTConfig

# Load training data
train_dataset = load_dataset('json', data_files='data/finetune_train_hf.jsonl', split='train')
val_dataset = load_dataset('json', data_files='data/finetune_val_hf.jsonl', split='train')

print(f"Training set: {len(train_dataset)} items")
print(f"Validation set: {len(val_dataset)} items")

# Training config
sft_config = SFTConfig(
    output_dir="./qwen2.5-7b-churn-lora",      # Output directory
    num_train_epochs=3,                          # Number of epochs
    per_device_train_batch_size=1,               # Per GPU batch size
    per_device_eval_batch_size=1,                # Evaluation batch size
    gradient_accumulation_steps=8,               # Gradient accumulation (effective batch = 8)
    optim="paged_adamw_8bit",                    # 8-bit optimizer to save memory
    learning_rate=2e-4,                          # QLoRA standard learning rate
    lr_scheduler_type="cosine",                  # Cosine annealing
    warmup_steps=6,                           # Warmup ratio
    weight_decay=0.01,                           # Weight decay
    fp16=False,                                   # A100 uses BF16 (more stable, no GradScaler needed)
    bf16=True,
    logging_steps=5,                             # Log every 5 steps
    eval_strategy="steps",                       # Evaluate by steps
    eval_steps=20,                               # Evaluate every 20 steps
    save_strategy="steps",                       # Save by steps
    save_steps=50,                               # Save every 50 steps
    save_total_limit=3,                          # Keep at most 3 checkpoints
    gradient_checkpointing=True,                 # Gradient checkpointing to save memory
    dataset_text_field="text",                   # Text field name in dataset
    report_to="none",                            # Do not upload to wandb
)

# Create trainer
trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
)

print(f"\nTraining config:")
print(f"  Effective batch size: {sft_config.per_device_train_batch_size * sft_config.gradient_accumulation_steps}")
print(f"  Total training steps: {len(train_dataset) // (sft_config.per_device_train_batch_size * sft_config.gradient_accumulation_steps) * sft_config.num_train_epochs}")

# Start training
print("\nStarting training...")
print("=" * 50)
train_result = trainer.train()

print("\nTraining complete ✓")
print(f"  Training loss: {train_result.training_loss:.4f}")
print(f"  Training time: {train_result.metrics['train_runtime']:.0f} seconds")

### Save LoRA Adapter

The fine-tuned LoRA adapter is only approximately **40 MB** (compared to the full model at 14 GB), making it easy to store and share.

Save locations:
1. Colab local: `./qwen2.5-7b-churn-lora/final`
2. Google Drive: `/content/drive/MyDrive/qwen2.5-7b-churn-lora` (persistent)

In [ ]:
# --------------------------------------------
# 6.3 Save LoRA Adapter
# ⚠️ Run on Google Colab
# --------------------------------------------

# Save locally
adapter_local_path = "./qwen2.5-7b-churn-lora/final"
trainer.save_model(adapter_local_path)
tokenizer.save_pretrained(adapter_local_path)
print(f"Adapter saved to: {adapter_local_path}")

# Save to Google Drive (persistent)
adapter_drive_path = "/content/drive/MyDrive/qwen2.5-7b-churn-lora"
os.makedirs(adapter_drive_path, exist_ok=True)
trainer.save_model(adapter_drive_path)
tokenizer.save_pretrained(adapter_drive_path)
print(f"Adapter backed up to Google Drive: {adapter_drive_path}")

# Show adapter size
import subprocess
result = subprocess.run(['du', '-sh', adapter_local_path], capture_output=True, text=True)
print(f"\nAdapter size: {result.stdout.strip()}")

# Release training-related memory
del trainer
gc.collect()
torch.cuda.empty_cache()

# Optional: Push to Hugging Face Hub
# from huggingface_hub import login
# login(token="your_hf_token")
# model.push_to_hub("your-username/qwen2.5-7b-churn-lora")
# tokenizer.push_to_hub("your-username/qwen2.5-7b-churn-lora")

print(f"\nGPU memory: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")
print("\n✓ Phase 6 complete - LoRA Adapter saved")

---

# Phase 7: Open-Source Model Integration into RAG Pipeline

> **Warning: Run on Google Colab (free T4 GPU)**

## Objective

Replace the Phase 3 base model with the **QLoRA fine-tuned Qwen2.5-7B-Instruct** to improve RAG output quality.

## Architecture Change

```
Original Architecture (Phase 3-4):
  hybrid_search() -> build_context() -> Qwen2.5-7B base (zero-shot) -> JSON parsing

New Architecture (Phase 7):
  hybrid_search() -> build_context() -> Qwen2.5-7B + LoRA (local) -> JSON parsing
```

## VRAM Estimate

| Component | VRAM |
|------|------|
| BGE Embedding Model | ~0.5 GB |
| Qwen2.5-7B + LoRA (4-bit) | ~4.5 GB |
| **Total** | **~5 GB** |

VRAM is sufficient in inference mode, T4 is fully capable.

In [ ]:
# ============================================
# Phase 7: Open-Source Model Integration into RAG Pipeline
# ⚠️ Run on Google Colab (T4 GPU)
# ============================================

# --------------------------------------------
# 7.1 Load Fine-tuned Model
# --------------------------------------------

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
import torch
import json
import re
import gc

# Clean up if previous model is still in memory
gc.collect()
torch.cuda.empty_cache()

# 4-bit quantization config (for inference)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

BASE_MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"
# Load adapter from Google Drive (persistent path)
ADAPTER_PATH = "/content/drive/MyDrive/qwen2.5-7b-churn-lora"
# Alternative: load from local
# ADAPTER_PATH = "./qwen2.5-7b-churn-lora/final"

print(f"Loading base model: {BASE_MODEL_NAME} (4-bit)...")
ft_tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_NAME, trust_remote_code=True)

ft_base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)

# Load LoRA adapter
print(f"Loading LoRA adapter: {ADAPTER_PATH}...")
ft_model = PeftModel.from_pretrained(ft_base_model, ADAPTER_PATH)
ft_model.eval()

print(f"\nFine-tuned model loaded ✓")
print(f"GPU memory: {torch.cuda.memory_allocated() / 1024**3:.1f} GB")

## 7.2 Define Local RAG Query Function

`rag_query_local()` has the same interface as the original `rag_query()`, but with LoRA fine-tuned weights loaded:

| Step | Original Method (Phase 3) | New Method (Phase 7) |
|------|------------------|------------------|
| Retrieval | `hybrid_search()` | `hybrid_search()` (unchanged) |
| Context | `build_context()` | `build_context()` (unchanged) |
| Generation | `model.generate()` (base) | `model.generate()` (base + LoRA) |
| Parsing | `json.loads()` | `json.loads()` + regex fallback |

### Enhanced JSON Parsing

Open-source models may add extra text around the JSON (e.g., "Here is the analysis:"), so a **regex fallback** was added to extract the JSON block.

In [ ]:
# --------------------------------------------
# 7.2 Define Local RAG Query Function
# ⚠️ Run on Google Colab
# --------------------------------------------

def rag_query_local(user_query, k=5, max_new_tokens=1024, use_finetuned=True):
    """
    Fine-tuned model RAG Query Pipeline (base + LoRA adapter)

    Args:
        user_query: User query
        k: Number of documents to retrieve
        max_new_tokens: Maximum tokens to generate
        use_finetuned: True for fine-tuned model, False for base model (for comparison)

    Returns:
        dict: Parsed JSON result
    """
    # Step 1: Retrieve relevant documents (same as original rag_query)
    search_results = hybrid_search(user_query, k=k)

    # Step 2: Build context (same as original rag_query)
    context = build_context(search_results, max_docs=k)

    # Step 3: Build prompt and generate with local model
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_TEMPLATE.format(query=user_query, context=context)},
    ]

    active_model = ft_model if use_finetuned else ft_base_model

    text = ft_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = ft_tokenizer(text, return_tensors="pt").to(active_model.device)

    with torch.no_grad():
        outputs = active_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=ft_tokenizer.eos_token_id,
        )

    generated_ids = outputs[0][inputs['input_ids'].shape[1]:]
    response_text = ft_tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    # Step 4: JSON parsing + regex fallback
    result = None
    try:
        result = json.loads(response_text)
    except json.JSONDecodeError:
        # Fallback: extract JSON block
        json_match = re.search(r'\{[\s\S]*\}', response_text)
        if json_match:
            try:
                result = json.loads(json_match.group())
            except json.JSONDecodeError:
                pass

    if result is None:
        result = {"error": "Failed to parse JSON", "raw_response": response_text}

    # Add retrieval metadata
    result["retrieved_docs"] = len(search_results)
    result["retrieved_customer_ids"] = [customer_ids[idx] for idx, _ in search_results]

    return result

print("rag_query_local() defined ✓")

## 7.3 Define Complete Analysis Function

`analyze_churn_local()` encapsulates the complete RAG workflow: Retrieval -> Generation -> Formatted Output -> Citation Validation.

Reuses existing `display_analysis()` and `validate_citations()` functions.

In [ ]:
# --------------------------------------------
# 7.3 Define Complete Analysis Function
# ⚠️ Run on Google Colab
# --------------------------------------------

# Reuse Phase 4 helper functions
def display_analysis(result):
    """Display analysis results in formatted style"""
    print("\n" + "=" * 60)
    print("CUSTOMER CHURN ANALYSIS REPORT")
    print("=" * 60)

    if "error" in result:
        print(f"Error: {result['error']}")
        if "raw_response" in result:
            print(f"Raw response: {result['raw_response'][:500]}")
        return

    print(f"\nSummary:")
    print(f"   {result.get('summary', 'N/A')}")

    print(f"\nTop Reasons for Churn:")
    for i, reason in enumerate(result.get('top_reasons', []), 1):
        print(f"   {i}. {reason}")

    print(f"\nRisk Level: {result.get('risk_level', 'N/A').upper()}")

    print(f"\nRecommended Actions:")
    for i, action in enumerate(result.get('actions', []), 1):
        print(f"   {i}. {action}")

    print(f"\nCitations (Customer IDs):")
    print(f"   {', '.join(result.get('citations', []))}")

    print(f"\nRetrieved Documents: {result.get('retrieved_docs', 0)}")
    print("=" * 60)

def normalize_customer_id(cid):
    """Normalize customer ID"""
    cid = cid.strip().lower()
    prefixes = ['customerid_', 'customer_id_', 'cid_', 'id_']
    for prefix in prefixes:
        if cid.startswith(prefix):
            cid = cid[len(prefix):]
    return cid

def validate_citations(result):
    """Validate whether citations come from retrieved results"""
    citations = result.get('citations', [])
    retrieved_ids = result.get('retrieved_customer_ids', [])

    retrieved_normalized = {normalize_customer_id(rid): rid for rid in retrieved_ids}

    valid_citations = []
    invalid_citations = []

    for cid in citations:
        normalized = normalize_customer_id(cid)
        if normalized in retrieved_normalized:
            valid_citations.append(cid)
        else:
            invalid_citations.append(cid)

    accuracy = len(valid_citations) / len(citations) if citations else 0

    return {
        "total_citations": len(citations),
        "valid_citations": valid_citations,
        "invalid_citations": invalid_citations,
        "accuracy": accuracy,
    }

def analyze_churn_local(query, use_finetuned=True):
    """
    Complete local churn analysis function

    Args:
        query: Analysis query
        use_finetuned: True for fine-tuned model, False for base model

    Returns:
        Analysis result dict
    """
    model_type = "Fine-tuned" if use_finetuned else "Base"
    print(f"Analyzing ({model_type}): {query}")
    print("-" * 50)

    result = rag_query_local(query, k=5, use_finetuned=use_finetuned)
    display_analysis(result)

    validation = validate_citations(result)
    print(f"\nCitation Accuracy: {validation['accuracy']*100:.1f}%")

    return result

print("analyze_churn_local() defined ✓")

## 7.4 End-to-End Test

Use 3 different types of queries to verify the complete RAG Pipeline with the local model.

In [ ]:
# --------------------------------------------
# 7.4 End-to-End Test
# ⚠️ Run on Google Colab
# --------------------------------------------

test_queries = [
    "Why are customers with fiber optic internet churning?",
    "What issues do senior citizens face with our services?",
    "What should we do to reduce churn among month-to-month customers?",
]

print("=" * 60)
print("Phase 7: End-to-End Test - Fine-tuned Model RAG Pipeline")
print("=" * 60)

test_results = []
for i, query in enumerate(test_queries, 1):
    print(f"\n{'='*60}")
    print(f"Test {i}/{len(test_queries)}")
    print(f"{'='*60}")
    result = analyze_churn_local(query, use_finetuned=True)
    test_results.append(result)

# Summarize test results
print("\n" + "=" * 60)
print("End-to-End Test Summary")
print("=" * 60)
for i, (query, result) in enumerate(zip(test_queries, test_results), 1):
    has_error = "error" in result
    json_valid = not has_error
    fields_ok = all(f in result for f in ['summary', 'top_reasons', 'risk_level', 'actions', 'citations']) if not has_error else False
    print(f"  Test {i}: JSON={'OK' if json_valid else 'FAIL'}  Fields={'Complete' if fields_ok else 'Missing'}  Query={query[:50]}...")

print("\n✓ Phase 7 complete - Open-source model RAG Pipeline verified")

---

# Phase 8: Evaluation & Comparison

> **Warning: Run on Google Colab (free T4 GPU)**

## Objective

Compare the performance of **Base model (zero-shot)** vs **QLoRA fine-tuned model** on the RAG task.

## Dual-Model Comparison Plan

| Model | Description |
|------|------|
| Qwen2.5-7B-Instruct (base) | Original model, zero-shot |
| Qwen2.5-7B-Instruct + LoRA | Fine-tuned model |

## Evaluation Metrics

| Metric | Description |
|------|------|
| JSON Format Compliance | Whether the response is valid JSON |
| Field Completeness | Whether all 5 required fields are present |
| Type Correctness | Whether field values and types match the schema |
| Citation Accuracy | Whether cited customer IDs come from retrieval results |
| Risk Level Alignment | Whether risk_level aligns with actual churn ratio |

## Test Set

10 diverse queries not used in training, covering different analysis dimensions.

In [ ]:
# ============================================
# Phase 8: Evaluation & Comparison
# ⚠️ Run on Google Colab (T4 GPU)
# ============================================

# --------------------------------------------
# 8.1 Define Test Set and Evaluation Functions
# --------------------------------------------

# 10 test queries not used in training
eval_queries = [
    {"query": "What are the top reasons for churn among customers with multiple services?", "category": "service"},
    {"query": "How do payment methods influence customer retention?", "category": "billing"},
    {"query": "What patterns exist in feedback from customers who stayed?", "category": "sentiment"},
    {"query": "Why do customers without online security churn more?", "category": "service"},
    {"query": "What is the relationship between tenure and customer satisfaction?", "category": "tenure"},
    {"query": "How effective is tech support in preventing churn?", "category": "service"},
    {"query": "What demographic factors contribute most to churn risk?", "category": "demographics"},
    {"query": "Compare customer satisfaction between paperless and non-paperless billing", "category": "comparison"},
    {"query": "What proactive measures can reduce churn for high-value customers?", "category": "action"},
    {"query": "What role does contract length play in customer loyalty?", "category": "contract"},
]

def evaluate_response(result, query_info):
    """
    Evaluate the quality of a single response

    Returns scores per dimension (0 or 1)
    """
    scores = {}

    # 1. JSON format compliance
    scores["json_valid"] = 0 if "error" in result else 1

    if scores["json_valid"] == 0:
        # JSON invalid, all other metrics are 0
        scores["fields_complete"] = 0
        scores["types_correct"] = 0
        scores["citation_accuracy"] = 0.0
        scores["risk_aligned"] = 0
        scores["response_length"] = 0
        return scores

    # 2. Field completeness
    required_fields = ['summary', 'top_reasons', 'risk_level', 'actions', 'citations']
    scores["fields_complete"] = 1 if all(f in result for f in required_fields) else 0

    # 3. Type correctness
    type_checks = [
        isinstance(result.get('summary'), str) and len(result.get('summary', '')) > 10,
        isinstance(result.get('top_reasons'), list) and len(result.get('top_reasons', [])) > 0,
        result.get('risk_level') in ['high', 'medium', 'low'],
        isinstance(result.get('actions'), list) and len(result.get('actions', [])) > 0,
        isinstance(result.get('citations'), list),
    ]
    scores["types_correct"] = 1 if all(type_checks) else 0

    # 4. Citation accuracy
    validation = validate_citations(result)
    scores["citation_accuracy"] = validation["accuracy"]

    # 5. Risk level alignment (based on actual churn ratio of retrieved customers)
    retrieved_ids = result.get("retrieved_customer_ids", [])
    if retrieved_ids:
        churned = sum(1 for cid in retrieved_ids
                      if cid in customer_ids and
                      df_with_feedback[df_with_feedback['customerID'] == cid]['Churn'].values[0] == 'Yes'
                      if len(df_with_feedback[df_with_feedback['customerID'] == cid]) > 0)
        churn_rate = churned / len(retrieved_ids)
        actual_risk = "high" if churn_rate > 0.5 else ("medium" if churn_rate > 0.25 else "low")
        scores["risk_aligned"] = 1 if result.get("risk_level") == actual_risk else 0
    else:
        scores["risk_aligned"] = 0

    # 6. Response detail level (total characters of summary + reasons + actions)
    detail_len = len(result.get('summary', ''))
    detail_len += sum(len(r) for r in result.get('top_reasons', []))
    detail_len += sum(len(a) for a in result.get('actions', []))
    scores["response_length"] = detail_len

    return scores

print(f"Test set: {len(eval_queries)} queries")
print("Evaluation functions defined ✓")

### Run Dual-Model Evaluation

For the same set of test queries, generate responses with both the **Base model** and **Fine-tuned model** and evaluate them.

In [ ]:
# --------------------------------------------
# 8.2 Run Dual-Model Evaluation
# ⚠️ Run on Google Colab
# --------------------------------------------

from tqdm import tqdm

# Store evaluation results
eval_results = {"base": [], "finetuned": []}
eval_scores = {"base": [], "finetuned": []}

for model_type, use_ft in [("finetuned", True), ("base", False)]:
    print(f"\n{'='*60}")
    print(f"Evaluating model: {'Fine-tuned (LoRA)' if use_ft else 'Base (Zero-shot)'}")
    print(f"{'='*60}")

    for q_info in tqdm(eval_queries, desc=model_type):
        result = rag_query_local(q_info["query"], k=5, use_finetuned=use_ft)
        scores = evaluate_response(result, q_info)

        eval_results[model_type].append(result)
        eval_scores[model_type].append(scores)

        torch.cuda.empty_cache()

# Summarize evaluation results
print("\n" + "=" * 60)
print("Evaluation Results Summary")
print("=" * 60)

metrics = ["json_valid", "fields_complete", "types_correct", "citation_accuracy", "risk_aligned"]
metric_names = {
    "json_valid": "JSON Format Compliance",
    "fields_complete": "Field Completeness",
    "types_correct": "Type Correctness",
    "citation_accuracy": "Citation Accuracy",
    "risk_aligned": "Risk Level Alignment",
}

print(f"\n{'Metric':<20} {'Base Model':>12} {'Fine-tuned':>12} {'Improvement':>10}")
print("-" * 56)

for metric in metrics:
    base_avg = np.mean([s[metric] for s in eval_scores["base"]])
    ft_avg = np.mean([s[metric] for s in eval_scores["finetuned"]])
    diff = ft_avg - base_avg
    print(f"{metric_names[metric]:<20} {base_avg:>11.1%} {ft_avg:>11.1%} {diff:>+9.1%}")

# Response detail level
base_len = np.mean([s["response_length"] for s in eval_scores["base"]])
ft_len = np.mean([s["response_length"] for s in eval_scores["finetuned"]])
print(f"{'Avg Response Length':<20} {base_len:>11.0f} {ft_len:>11.0f} {ft_len-base_len:>+9.0f}")

### Visualization Comparison

Generate two sets of visualizations:
1. **Quality Metrics Bar Chart**: Compare 5 evaluation dimensions
2. **Response Detail Box Plot**: Compare average response lengths
3. **Per-Query Comparison Table**: Detailed scores for each query

In [ ]:
# --------------------------------------------
# 8.3 Visualization Comparison
# ⚠️ Run on Google Colab
# --------------------------------------------

import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['figure.dpi'] = 120

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# === Chart 1: Quality Metrics Comparison ===
ax1 = axes[0]
x = np.arange(len(metrics))
width = 0.35

base_scores_avg = [np.mean([s[m] for s in eval_scores["base"]]) for m in metrics]
ft_scores_avg = [np.mean([s[m] for s in eval_scores["finetuned"]]) for m in metrics]

bars1 = ax1.bar(x - width/2, base_scores_avg, width, label='Base (Zero-shot)', color='#FF6B6B', alpha=0.8)
bars2 = ax1.bar(x + width/2, ft_scores_avg, width, label='Fine-tuned (QLoRA)', color='#4ECDC4', alpha=0.8)

ax1.set_xlabel('Evaluation Metrics')
ax1.set_ylabel('Score')
ax1.set_title('Model Quality Comparison')
ax1.set_xticks(x)
ax1.set_xticklabels(['JSON\nValid', 'Fields\nComplete', 'Types\nCorrect', 'Citation\nAccuracy', 'Risk\nAligned'],
                     fontsize=8)
ax1.set_ylim(0, 1.15)
ax1.legend(loc='upper right', fontsize=8)

# Add value labels
for bar in bars1:
    height = bar.get_height()
    ax1.annotate(f'{height:.0%}', xy=(bar.get_x() + bar.get_width()/2, height),
                xytext=(0, 3), textcoords="offset points", ha='center', va='bottom', fontsize=7)
for bar in bars2:
    height = bar.get_height()
    ax1.annotate(f'{height:.0%}', xy=(bar.get_x() + bar.get_width()/2, height),
                xytext=(0, 3), textcoords="offset points", ha='center', va='bottom', fontsize=7)

# === Chart 2: Response Detail Comparison ===
ax2 = axes[1]
base_lengths = [s["response_length"] for s in eval_scores["base"]]
ft_lengths = [s["response_length"] for s in eval_scores["finetuned"]]

bp = ax2.boxplot([base_lengths, ft_lengths],
                  labels=['Base (Zero-shot)', 'Fine-tuned (QLoRA)'],
                  patch_artist=True,
                  boxprops=dict(alpha=0.8))
bp['boxes'][0].set_facecolor('#FF6B6B')
bp['boxes'][1].set_facecolor('#4ECDC4')

ax2.set_ylabel('Response Length (chars)')
ax2.set_title('Response Detail Comparison')

# Add mean markers
ax2.scatter([1, 2], [np.mean(base_lengths), np.mean(ft_lengths)],
            color='black', marker='D', s=50, zorder=5, label='Mean')
ax2.legend(fontsize=8)

plt.tight_layout()

# Save charts
os.makedirs("data", exist_ok=True)
plt.savefig("data/model_comparison.png", dpi=150, bbox_inches='tight')

# Also save to Google Drive
drive_data_dir = '/content/drive/MyDrive/lora_finetune_data'
os.makedirs(drive_data_dir, exist_ok=True)
plt.savefig(os.path.join(drive_data_dir, 'model_comparison.png'), dpi=150, bbox_inches='tight')

plt.show()
print("\nCharts saved to data/model_comparison.png")

In [ ]:
# --------------------------------------------
# 8.4 Per-Query Comparison Table
# ⚠️ Run on Google Colab
# --------------------------------------------

print("=" * 90)
print("Per-Query Comparison Table")
print("=" * 90)
print(f"{'#':<3} {'Query':<50} {'Model':<12} {'JSON':>5} {'Fields':>5} {'Types':>5} {'Citations':>6} {'Risk':>5}")
print("-" * 90)

for i, q_info in enumerate(eval_queries):
    query_short = q_info["query"][:48] + ".." if len(q_info["query"]) > 48 else q_info["query"]

    base_s = eval_scores["base"][i]
    ft_s = eval_scores["finetuned"][i]

    print(f"{i+1:<3} {query_short:<50} {'Base':<12} "
          f"{'OK' if base_s['json_valid'] else 'FAIL':>5} "
          f"{'OK' if base_s['fields_complete'] else 'FAIL':>5} "
          f"{'OK' if base_s['types_correct'] else 'FAIL':>5} "
          f"{base_s['citation_accuracy']:>5.0%} "
          f"{'OK' if base_s['risk_aligned'] else 'FAIL':>5}")

    print(f"{'':3} {'':50} {'LoRA':<12} "
          f"{'OK' if ft_s['json_valid'] else 'FAIL':>5} "
          f"{'OK' if ft_s['fields_complete'] else 'FAIL':>5} "
          f"{'OK' if ft_s['types_correct'] else 'FAIL':>5} "
          f"{ft_s['citation_accuracy']:>5.0%} "
          f"{'OK' if ft_s['risk_aligned'] else 'FAIL':>5}")
    print()

# Final summary
print("=" * 60)
print("Phase 8 Evaluation Complete")
print("=" * 60)

base_overall = np.mean([np.mean([s[m] for m in metrics]) for s in eval_scores["base"]])
ft_overall = np.mean([np.mean([s[m] for m in metrics]) for s in eval_scores["finetuned"]])

print(f"\n  Base model overall score:    {base_overall:.1%}")
print(f"  Fine-tuned model overall score:    {ft_overall:.1%}")
print(f"  Overall improvement:            {ft_overall - base_overall:+.1%}")

print(f"\nProject complete:")
print(f"  Phase 1-4: RAG System (Qwen2.5-7B-Instruct, open-source)")
print(f"  Phase 5:   Training Data Preparation (Colab, free)")
print(f"  Phase 6:   QLoRA Fine-tuning (Colab, free)")
print(f"  Phase 7:   Open-source Model Integration (Colab, free)")
print(f"  Phase 8:   Evaluation & Comparison (Colab, free)")
print(f"\nAll phases completed, entire pipeline uses open-source models, zero cost ✓")